# Generated by Django 6.0.2 on 2026-02-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='analyticdimension',
            name='analytic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='analytics.analytic'),
        ),
        migrations.AddField(
            model_name='analyticresult',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='analytics.analyticdimension'),
        ),
        migrations.AddField(
            model_name='analyticrun',
            name='analytic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analytics.analytic'),
        ),
    ]
