STOCK_SCHEMA_COLUMNS_CATALOG = [
    {
        'title': 'Ticker',
        'data_type': 'string',
        'source': 'asset',
        'source_field': 'ticker',
        'editable': False,
        'is_deletable': False,
        'is_default': True,
    },
    {
        'title': 'Quantity',
        'data_type': 'decimal',
        'source': 'holding',
        'source_field': 'quantity',
        'decimal_spaces': 4,
        'editable': True,
        'is_deletable': False,
        'is_default': True,
    },
    {
        'title': 'Price',
        'data_type': 'decimal',
        'source': 'asset',
        'source_field': 'price',
        'decimal_spaces': 2,
        'editable': True,
        'is_deletable': False,
        'is_default': True,
    },
    {
        'title': 'Current Value',
        'data_type': 'decimal',
        'source': 'calculated',
        'source_field': 'current_value',
        'decimal_spaces': 2,
        'editable': False,
        'is_deletable': False,
        'formula': 'quantity * price',
        'is_default': True,
    },
    {
        'title': 'Market Cap',
        'data_type': 'decimal',
        'source': 'asset',
        'source_field': 'market_cap',
        'decimal_spaces': 2,
        'editable': False,
        'is_deletable': True,
        'is_default': False,
    },
    {
        'title': 'P/E Ratio',
        'data_type': 'decimal',
        'source': 'asset',
        'source_field': 'pe_ratio',
        'decimal_spaces': 2,
        'editable': False,
        'is_deletable': True,
        'is_default': False,
    },
]
