# Generated by Django 6.0.3 on 2026-04-03 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_profile_country_code_authevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null means a common system asset type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='users.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, help_text='Optional ticker, symbol, or shorthand identifier.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Flexible asset-specific metadata.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null means a common/public asset. Set means a private user-owned asset.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='users.profile')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='assettype',
            index=models.Index(fields=['created_by', 'name'], name='assets_asse_created_303782_idx'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', True)), fields=('name',), name='uniq_system_asset_type_name'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', True)), fields=('slug',), name='uniq_system_asset_type_slug'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False)), fields=('created_by', 'name'), name='uniq_user_asset_type_name'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False)), fields=('created_by', 'slug'), name='uniq_user_asset_type_slug'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'name'], name='assets_asse_asset_t_e69514_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['owner', 'asset_type'], name='assets_asse_owner_i_9e076c_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['symbol'], name='assets_asse_symbol_71b57b_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_active'], name='assets_asse_is_acti_7e009b_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True), models.Q(('symbol', ''), _negated=True)), fields=('asset_type', 'symbol'), name='uniq_public_asset_symbol_per_type'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'asset_type', 'name'), name='uniq_private_asset_name_per_owner_and_type'),
        ),
    ]
