# Generated by Django 6.0.3 on 2026-04-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fmp', 'FMP')], default='fmp', max_length=50)),
                ('provider_symbol', models.CharField(blank=True, help_text='Provider-facing symbol used for quotes/profile lookups.', max_length=50)),
                ('provider_identifier', models.CharField(blank=True, help_text='Optional stable provider identifier if available.', max_length=100)),
                ('status', models.CharField(choices=[('untracked', 'Untracked'), ('tracked', 'Tracked'), ('stale', 'Stale'), ('unresolved', 'Unresolved')], default='untracked', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='assets.asset')),
            ],
            options={
                'ordering': ['asset__name'],
                'indexes': [models.Index(fields=['provider', 'status'], name='assets_asse_provide_b0606e_idx'), models.Index(fields=['provider', 'provider_symbol'], name='assets_asse_provide_d0d412_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_symbol', ''), _negated=True), fields=('provider', 'provider_symbol'), name='uniq_asset_market_data_provider_symbol'), models.UniqueConstraint(condition=models.Q(('provider_identifier', ''), _negated=True), fields=('provider', 'provider_identifier'), name='uniq_asset_market_data_provider_identifier')],
            },
        ),
    ]
