# Generated by Django 6.0.3 on 2026-04-06 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetmarketdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=18, max_digits=40)),
                ('change', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='FMP', max_length=50)),
                ('as_of', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='assets.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'as_of'], name='assets_asse_source_3f67fa_idx')],
            },
        ),
    ]
