# Generated by Django 6.0.3 on 2026-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmarketdata',
            name='cik',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetmarketdata',
            name='cusip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetmarketdata',
            name='isin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetmarketdata',
            name='last_seen_exchange',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetmarketdata',
            name='last_seen_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetmarketdata',
            name='last_seen_symbol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assetmarketdata',
            name='status',
            field=models.CharField(choices=[('untracked', 'Untracked'), ('tracked', 'Tracked'), ('stale', 'Stale'), ('unresolved', 'Unresolved'), ('needs_review', 'Needs Review')], default='untracked', max_length=20),
        ),
    ]
