# Generated by Django 6.0.3 on 2026-04-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetmarketdata_cik_assetmarketdata_cusip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDividendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_dividend_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('last_dividend_date', models.DateField(blank=True, null=True)),
                ('last_dividend_frequency', models.CharField(blank=True, max_length=30, null=True)),
                ('last_dividend_is_special', models.BooleanField(default=False)),
                ('regular_dividend_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('regular_dividend_date', models.DateField(blank=True, null=True)),
                ('regular_dividend_frequency', models.CharField(blank=True, max_length=30, null=True)),
                ('trailing_12m_dividend', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('trailing_12m_cashflow', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('forward_annual_dividend', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('trailing_dividend_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('forward_dividend_yield', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('cadence_status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('broken', 'Broken'), ('none', 'None')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('confident', 'Confident'), ('uncertain', 'Uncertain'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_snapshot', to='assets.asset')),
            ],
            options={
                'ordering': ['asset__name'],
                'indexes': [models.Index(fields=['status', 'cadence_status'], name='assets_asse_status_60a958_idx'), models.Index(fields=['last_computed_at'], name='assets_asse_last_co_09e378_idx')],
            },
        ),
    ]
