# Generated by Django 6.0.2 on 2026-02-19 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_brokeragesecret'),
        ('portfolios', '0004_remove_is_main'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_value_identifier', models.SlugField(default='current_value', help_text='Schema identifier used as the base value for allocation math.', max_length=100)),
                ('base_scope', models.CharField(choices=[('total_portfolio', 'Total Portfolio'), ('account_type', 'Single Account Type')], default='total_portfolio', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(blank=True, help_text='Required only when base_scope=account_type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_plans', to='accounts.accounttype')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_plans', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='allocations.allocationplan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_runs', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='allocations.allocationscenario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_identifier', models.SlugField(help_text='Analytics dimension name (slug).', max_length=100)),
                ('source_analytic_name', models.SlugField(blank=True, help_text='Optional analytics name to disambiguate dimension source.', max_length=100, null=True)),
                ('denominator_mode', models.CharField(choices=[('base_scope_total', 'Percent of Base Scope'), ('absolute_only', 'Absolute Amount')], default='base_scope_total', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='allocations.allocationscenario')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('target_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('min_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('max_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='allocations.allocationdimension')),
            ],
            options={
                'ordering': ['display_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AllocationGapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_key_snapshot', models.SlugField(max_length=100)),
                ('bucket_label_snapshot', models.CharField(max_length=150)),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gap_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_percent', models.DecimalField(decimal_places=6, max_digits=9)),
                ('target_percent', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gap_percent', models.DecimalField(decimal_places=6, max_digits=9)),
                ('holding_count', models.PositiveIntegerField(default=0)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='allocations.allocationdimension')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='allocations.allocationevaluationrun')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='allocations.allocationtarget')),
            ],
            options={
                'ordering': ['-gap_value'],
            },
        ),
        migrations.AddIndex(
            model_name='allocationplan',
            index=models.Index(fields=['portfolio', 'is_active'], name='allocations_portfol_818ffc_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationplan',
            constraint=models.UniqueConstraint(fields=('portfolio', 'name'), name='uniq_allocation_plan_name_per_portfolio'),
        ),
        migrations.AddIndex(
            model_name='allocationscenario',
            index=models.Index(fields=['plan', 'is_active'], name='allocations_plan_id_bfea3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationscenario',
            constraint=models.UniqueConstraint(fields=('plan', 'name'), name='uniq_allocation_scenario_name_per_plan'),
        ),
        migrations.AddIndex(
            model_name='allocationevaluationrun',
            index=models.Index(fields=['scenario', '-created_at'], name='allocations_scenari_b1ac9a_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationevaluationrun',
            index=models.Index(fields=['status'], name='allocations_status_6fb6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationdimension',
            index=models.Index(fields=['scenario', 'is_active', 'display_order'], name='allocations_scenari_309cd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationdimension',
            constraint=models.UniqueConstraint(fields=('scenario', 'name'), name='uniq_allocation_dimension_name_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='allocationtarget',
            constraint=models.UniqueConstraint(fields=('dimension', 'key'), name='uniq_allocation_target_key_per_dimension'),
        ),
        migrations.AddIndex(
            model_name='allocationgapresult',
            index=models.Index(fields=['run', 'dimension'], name='allocations_run_id_92f4c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationgapresult',
            constraint=models.UniqueConstraint(fields=('run', 'dimension', 'bucket_key_snapshot'), name='uniq_allocation_gap_bucket_per_run_dimension'),
        ),
    ]
