EQUITY_PROFILE_MAP = {
    "exchangeShortName": "exchange",
    "exchange": "exchange_full_name",
    "currency": "currency",
    "country": "country",
    "isin": "isin",
    "cusip": "cusip",
    "cik": "cik",
    "ipoDate": "ipo_date",
    "sector": "sector",
    "industry": "industry",
    "isEtf": "is_etf",
    "isAdr": "is_adr",
    "isFund": "is_mutual_fund",
    "fundFamily": "fund_family",
    "category": "fund_category",
    "inceptionDate": "inception_date",
    "totalAssets": "total_assets",
    "turnoverRatio": "turnover_ratio",
    "underlyingIndex": "underlying_index",
    "aum": "aum",
    "holdingsCount": "holdings_count",
    "trackingError": "tracking_error",
    "premiumDiscount": "premium_discount",
    "parValue": "preferred_par_value",
    "couponRate": "preferred_coupon_rate",
    "callDate": "call_date",
    "esgScore": "esg_score",
    "carbonIntensity": "carbon_intensity",
    "nav": "nav",
    "expenseRatio": "expense_ratio",
    "name": "asset__name",  # goes on Asset, not EquityDetail
    "symbol": "asset__symbol",
}

EQUITY_QUOTE_MAP = {
    "price": "last_price",
    "open": "open_price",
    "dayHigh": "high_price",
    "dayLow": "low_price",
    "previousClose": "previous_close_price",
    "volume": "volume",
    "avgVolume": "average_volume",
    "marketCap": "market_cap",
    "sharesOutstanding": "shares_outstanding",
    "beta": "beta",
    "eps": "eps",
    "pe": "pe_ratio",
    "pb": "pb_ratio",
    "ps": "ps_ratio",
    "peg": "peg_ratio",
    "lastDiv": "dividend_per_share",
    "yield": "dividend_yield",
    "dividendFrequency": "dividend_frequency",
    "exDividendDate": "ex_dividend_date",
    "payoutRatio": "dividend_payout_ratio",
}
