EQUITY_PROFILE_MAP = {
    "exchangeShortName": "exchange",
    "exchange": "exchange_full_name",
    "currency": "asset__currency",
    "country": "country",
    "ipoDate": "ipo_date",
    "sector": "sector",
    "industry": "industry",
    "isEtf": "is_etf",
    "isAdr": "is_adr",
    "isFund": "is_mutual_fund",
    "companyName": "asset__name",
}

EQUITY_QUOTE_MAP = {
    "price": "last_price",
    "open": "open_price",
    "dayHigh": "high_price",
    "dayLow": "low_price",
    "previousClose": "previous_close_price",
    "volume": "volume",
    "avgVolume": "average_volume",
    "marketCap": "market_cap",
    "eps": "eps",
    "pe": "pe_ratio",
    "pb": "pb_ratio",
    "lastDiv": "dividend_per_share",
    "yield": "dividend_yield",
    "dividendFrequency": "dividend_frequency",
    "exDividendDate": "ex_dividend_date",
}
