# Generated by Django 5.2.3 on 2025-06-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_investmenttheme_alter_stockholding_investment_theme'),
        ('portfolios', '0002_delete_fxrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentTheme',
        ),
    ]
