# Generated by Django 6.0.2 on 2026-02-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('broker', models.CharField(blank=True, help_text='Optional broker name.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['portfolio', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Annual contribution limit for this user (if applicable).', max_digits=20, null=True)),
                ('carry_forward_room', models.DecimalField(blank=True, decimal_places=2, help_text='Unused contribution room carried forward.', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['definition__name'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='System identifier (only for system-defined account types).', null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('tax_deferred', 'Tax-Deferred'), ('tax_exempt', 'Tax-Exempt')], default='taxable', max_length=50)),
                ('all_countries', models.BooleanField(default=False, help_text='If true, this classification applies globally (all countries).')),
                ('is_system', models.BooleanField(default=True, help_text='True if this is a built-in classification available globally.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_ticker', models.CharField(blank=True, db_index=True, help_text='Ticker used when this holding was market-backed.', max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=30, default=0, help_text='Total quantity of this asset held in the account.', max_digits=50)),
                ('average_purchase_price', models.DecimalField(blank=True, decimal_places=30, help_text='Weighted average purchase price per unit.', max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account', 'asset'],
            },
        ),
    ]
