# Generated by Django 5.2.8 on 2025-11-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('equity_self', 'Brokerage Account'), ('crypto_wallet', 'Crypto Wallet'), ('metal_storage', 'Precious Metals Account'), ('bond_broker', 'Bond Brokerage Account'), ('bond_trust', 'Bond Trust Account'), ('real_estate', 'Real Estate Holding'), ('custom', 'Custom Account')], db_index=True, max_length=50)),
                ('broker', models.CharField(blank=True, help_text='Broker name (only used for brokered accounts such as equity or crypto).', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['portfolio', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Annual contribution limit for this user (if applicable).', max_digits=20, null=True)),
                ('carry_forward_room', models.DecimalField(blank=True, decimal_places=2, help_text='Unused contribution room carried forward.', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['definition__name'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('tax_deferred', 'Tax-Deferred'), ('tax_exempt', 'Tax-Exempt')], default='taxable', max_length=50)),
                ('all_countries', models.BooleanField(default=False, help_text='If true, this classification applies globally (all countries).')),
                ('jurisdictions', models.JSONField(blank=True, default=list, help_text="List of ISO country codes (e.g., ['US'], ['CA'], ['GB']).")),
                ('is_system', models.BooleanField(default=True, help_text='True if this is a built-in classification available globally.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
