# Generated by Django 5.2.4 on 2025-07-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('broker', models.CharField(blank=True, help_text='Brokerage platform (e.g. Robinhood, Interactive Brokers, etc.)', max_length=100, null=True)),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('tax_deferred', 'Tax-Deferred'), ('tax_exempt', 'Tax-Exempt')], default='taxable', max_length=50)),
                ('account_type', models.CharField(choices=[('individual', 'Individual'), ('retirement', 'Retirement'), ('speculative', 'Speculative'), ('dividend', 'Dividend Focus')], default='individual', help_text='Purpose or strategy of the account.', max_length=50)),
                ('currency', models.CharField(blank=True, choices=[('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Yuan Renminbi'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('INR', 'Indian Rupee'), ('JPY', 'Yen'), ('USD', 'US Dollar')], max_length=3, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('strategy', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfManagedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('broker', models.CharField(blank=True, help_text='Brokerage platform (e.g. Robinhood, Interactive Brokers, etc.)', max_length=100, null=True)),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('tax_deferred', 'Tax-Deferred'), ('tax_exempt', 'Tax-Exempt')], default='taxable', max_length=50)),
                ('account_type', models.CharField(choices=[('individual', 'Individual'), ('retirement', 'Retirement'), ('speculative', 'Speculative'), ('dividend', 'Dividend Focus')], default='individual', help_text='Purpose or strategy of the account.', max_length=50)),
                ('currency', models.CharField(blank=True, choices=[('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Yuan Renminbi'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('INR', 'Indian Rupee'), ('JPY', 'Yen'), ('USD', 'US Dollar')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('is_lending_account', models.BooleanField(default=False)),
                ('is_insured', models.BooleanField(default=False)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
