# Generated by Django 5.2.5 on 2025-08-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_accounts', to='portfolios.stockportfolio'),
        ),
        migrations.AddField(
            model_name='storagefacility',
            name='metals_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_facilities', to='portfolios.metalportfolio'),
        ),
        migrations.AddConstraint(
            model_name='stockaccount',
            constraint=models.UniqueConstraint(fields=('stock_portfolio', 'name'), name='unique_stockaccount_name_in_portfolio'),
        ),
    ]
