# Generated by Django 5.2.5 on 2025-08-29 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='crypto_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to='portfolios.cryptoportfolio'),
        ),
        migrations.AddField(
            model_name='customaccount',
            name='custom_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='portfolios.customportfolio'),
        ),
        migrations.AddField(
            model_name='customaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.customaccount'),
        ),
        migrations.AddField(
            model_name='managedaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_accounts', to='portfolios.stockportfolio'),
        ),
        migrations.AddField(
            model_name='selfmanagedaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_managed_accounts', to='portfolios.stockportfolio'),
        ),
        migrations.AddField(
            model_name='storagefacility',
            name='metal_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_facilities', to='portfolios.metalportfolio'),
        ),
        migrations.AddConstraint(
            model_name='cryptowallet',
            constraint=models.UniqueConstraint(fields=('crypto_portfolio', 'name'), name='unique_cryptowallet_name_in_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='customaccount',
            constraint=models.UniqueConstraint(fields=('custom_portfolio', 'parent', 'name'), name='uniq_custom_account_name_within_parent'),
        ),
        migrations.AddConstraint(
            model_name='managedaccount',
            constraint=models.UniqueConstraint(fields=('stock_portfolio', 'name'), name='unique_managedaccount_name_in_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='selfmanagedaccount',
            constraint=models.UniqueConstraint(fields=('stock_portfolio', 'name'), name='unique_selfmanagedstockaccount_name_in_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='storagefacility',
            constraint=models.UniqueConstraint(fields=('metal_portfolio', 'name'), name='unique_storagefacility_name_in_portfolio'),
        ),
    ]
