# Generated by Django 5.2.6 on 2025-09-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('stock_self', 'Stock Self'), ('stock_managed', 'Stock Managed'), ('crypto_wallet', 'Crypto Wallet'), ('metal_storage', 'Metal Storage'), ('custom', 'Custom')], db_index=True, help_text='Specific account type (e.g. stock_self, stock_managed, crypto_wallet).', max_length=50),
        ),
    ]
