# Generated by Django 5.2.5 on 2025-08-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managedaccount',
            options={'verbose_name': 'Managed Account'},
        ),
        migrations.AlterModelOptions(
            name='selfmanagedaccount',
            options={'verbose_name': 'Self-Managed Account'},
        ),
    ]
