# Generated by Django 6.0.1 on 2026-01-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('assets', '0001_initial'),
        ('fx', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclassification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_classifications', to='users.profile'),
        ),
        migrations.AddField(
            model_name='account',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='User-specific classification (e.g., TFSA, RRSP, 401k).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.accountclassification'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='allowed_asset_types',
            field=models.ManyToManyField(blank=True, help_text='What asset types can be held in accounts of this type.', related_name='account_types', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(help_text='The type of account (brokerage, crypto wallet, real estate container, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.accounttype'),
        ),
        migrations.AddField(
            model_name='classificationdefinition',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Countries where this classification is applicable.', related_name='classification_definitions', to='fx.country'),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='accounts.classificationdefinition'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('portfolio', 'account_type', 'name'), name='uniq_account_name_in_portfolio_per_type'),
        ),
        migrations.AlterUniqueTogether(
            name='accountclassification',
            unique_together={('profile', 'definition')},
        ),
    ]
