# Generated by Django 5.2.6 on 2025-09-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclassification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_classifications', to='users.profile'),
        ),
        migrations.AddField(
            model_name='account',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='User-specific classification (e.g., TFSA, RRSP, 401k).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.accountclassification'),
        ),
        migrations.AddField(
            model_name='accountclassification',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='accounts.classificationdefinition'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('portfolio', 'name'), name='uniq_account_name_in_portfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='accountclassification',
            unique_together={('profile', 'definition')},
        ),
    ]
