# Generated by Django 5.2.6 on 2025-09-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('assets', '0003_remove_preciousmetalholding_investment_theme_and_more'),
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CryptoWallet',
            new_name='CryptoAccount',
        ),
        migrations.RenameModel(
            old_name='StorageFacility',
            new_name='MetalAccount',
        ),
    ]
