# Generated by Django 5.2.6 on 2025-09-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
    ]
