# Generated by Django 5.2.5 on 2025-08-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_managedaccount_options_and_more'),
        ('portfolios', '0003_cryptoportfolio_customportfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagefacility',
            old_name='metals_portfolio',
            new_name='metal_portfolio',
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('crypto_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to='portfolios.cryptoportfolio')),
            ],
            options={
                'verbose_name': 'Crypto Wallet',
                'constraints': [models.UniqueConstraint(fields=('crypto_portfolio', 'name'), name='unique_cryptowallet_name_in_portfolio')],
            },
        ),
        migrations.CreateModel(
            name='CustomAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('depth', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('custom_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='portfolios.customportfolio')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.customaccount')),
            ],
            options={
                'verbose_name': 'Custom Account',
                'constraints': [models.UniqueConstraint(fields=('custom_portfolio', 'parent', 'name'), name='uniq_custom_account_name_within_parent')],
            },
        ),
    ]
