# Generated by Django 5.2.8 on 2025-11-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('fx', '0002_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationdefinition',
            name='jurisdictions',
        ),
        migrations.AddField(
            model_name='classificationdefinition',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Countries where this classification is applicable.', related_name='classification_definitions', to='fx.country'),
        ),
    ]
