# Generated by Django 6.0.1 on 2026-01-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('assets', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={},
        ),
        migrations.AddField(
            model_name='accounttype',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this account type if user-defined.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_account_types', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='allowed_asset_types',
            field=models.ManyToManyField(blank=True, related_name='account_types', to='assets.assettype'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='slug',
            field=models.SlugField(blank=True, help_text='System identifier (only for system-defined account types).', null=True),
        ),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('slug',), name='uniq_system_accounttype_slug'),
        ),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', False)), fields=('owner', 'name'), name='uniq_user_accounttype_name'),
        ),
    ]
