# Generated by Django 5.2.5 on 2025-08-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_managedaccount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedaccount',
            name='active_schema',
        ),
        migrations.RemoveField(
            model_name='selfmanagedaccount',
            name='active_schema',
        ),
    ]
