# Generated by Django 5.2.6 on 2025-09-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_cryptowallet_cryptoaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoaccount',
            name='crypto_portfolio',
        ),
        migrations.RemoveField(
            model_name='customaccount',
            name='custom_portfolio',
        ),
        migrations.RemoveField(
            model_name='customaccount',
            name='parent',
        ),
        migrations.RemoveConstraint(
            model_name='managedaccount',
            name='unique_managedaccount_name_in_portfolio',
        ),
        migrations.RemoveConstraint(
            model_name='metalaccount',
            name='unique_storagefacility_name_in_portfolio',
        ),
        migrations.RemoveConstraint(
            model_name='selfmanagedaccount',
            name='unique_selfmanagedstockaccount_name_in_portfolio',
        ),
        migrations.RemoveField(
            model_name='managedaccount',
            name='stock_portfolio',
        ),
        migrations.RemoveField(
            model_name='metalaccount',
            name='metal_portfolio',
        ),
        migrations.RemoveField(
            model_name='selfmanagedaccount',
            name='stock_portfolio',
        ),
    ]
