# Generated by Django 6.0 on 2025-12-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('allows_multiple', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('allowed_asset_types', models.ManyToManyField(blank=True, help_text='What asset types can be held in accounts of this type.', related_name='account_types', to='assets.assettype')),
            ],
            options={
                'ordering': ['display_order', 'slug'],
            },
        ),
    ]
