# Generated by Django 5.2.6 on 2025-09-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountclassification',
            options={'ordering': ['definition__name']},
        ),
        migrations.RemoveField(
            model_name='accountclassification',
            name='nickname',
        ),
    ]
