# Generated by Django 5.2.7 on 2025-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='broker',
            field=models.CharField(blank=True, help_text='Broker name (only used for brokered accounts such as equity or crypto).', max_length=100, null=True),
        ),
    ]
