# Generated by Django 5.2.6 on 2025-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('equity_self', 'Equity Self'), ('equity_managed', 'Equity Managed'), ('crypto_wallet', 'Crypto Wallet'), ('metal_storage', 'Metal Storage'), ('bond_broker', 'Bond Broker'), ('bond_trust', 'Bond Trust'), ('real_estate', 'Real Estate'), ('custom', 'Custom')], db_index=True, help_text='Specific account type (e.g. stock_self, stock_managed, crypto_wallet).', max_length=50),
        ),
    ]
