# Generated by Django 5.2.6 on 2025-09-05 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_cryptoaccount_crypto_portfolio_and_more'),
        ('portfolios', '0003_alter_customportfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedaccount',
            name='subportfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managed_accounts', to='portfolios.subportfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metalaccount',
            name='subportfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_facilities', to='portfolios.subportfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selfmanagedaccount',
            name='subportfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='self_managed_accounts', to='portfolios.subportfolio'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='managedaccount',
            constraint=models.UniqueConstraint(fields=('subportfolio', 'name'), name='unique_managedaccount_name_in_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='metalaccount',
            constraint=models.UniqueConstraint(fields=('subportfolio', 'name'), name='unique_storagefacility_name_in_subportfolio'),
        ),
        migrations.AddConstraint(
            model_name='selfmanagedaccount',
            constraint=models.UniqueConstraint(fields=('subportfolio', 'name'), name='unique_selfmanagedstockaccount_name_in_portfolio'),
        ),
        migrations.DeleteModel(
            name='CryptoAccount',
        ),
        migrations.DeleteModel(
            name='CustomAccount',
        ),
    ]
