# Generated by Django 6.0.1 on 2026-01-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounttype_options_accounttype_owner_and_more'),
        ('assets', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_account_types', to='users.profile'),
        ),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('name',), name='uniq_system_accounttype_name'),
        ),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='accounttype_owner_required_if_not_system'),
        ),
    ]
