# Generated by Codex on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_transactions_reconciliation_and_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationissue",
            name="resolution_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("keep_internal", "Keep Internal"),
                    ("align_to_external", "Align To External"),
                    ("adjust_internal_quantity", "Adjust Internal Quantity"),
                    ("ignore", "Ignore"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationissue",
            name="resolution_note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]

