# Generated by Django 5.2.5 on 2025-08-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_metals_portfolio_storagefacility_metal_portfolio_and_more'),
        ('portfolios', '0003_cryptoportfolio_customportfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagefacility',
            options={'verbose_name': 'Storage Facility'},
        ),
        migrations.RemoveField(
            model_name='storagefacility',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='storagefacility',
            name='is_insured',
        ),
        migrations.RemoveField(
            model_name='storagefacility',
            name='is_lending_account',
        ),
        migrations.AddConstraint(
            model_name='storagefacility',
            constraint=models.UniqueConstraint(fields=('metal_portfolio', 'name'), name='unique_storagefacility_name_in_portfolio'),
        ),
    ]
