# Generated by Django 6.0 on 2025-12-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['slug']},
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='display_order',
        ),
    ]
