# Generated by Django 5.2.6 on 2025-09-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountclassification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['portfolio', 'name']},
        ),
    ]
