# Generated by Django 5.2.6 on 2025-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationdefinition',
            name='jurisdiction',
        ),
        migrations.AddField(
            model_name='classificationdefinition',
            name='jurisdictions',
            field=models.JSONField(blank=True, default=list, help_text="List of jurisdictions where this classification applies. Use ISO country codes (e.g., ['US'], ['CA'], ['GB']) or ['*'] for global."),
        ),
    ]
