# Generated by Django 6.0 on 2025-12-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(help_text='The type of account (brokerage, crypto wallet, real estate container, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.accounttype'),
        ),
        migrations.AlterField(
            model_name='account',
            name='broker',
            field=models.CharField(blank=True, help_text='Optional broker name.', max_length=100, null=True),
        ),
    ]
