# Generated by Django 6.0.1 on 2026-01-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accounttype_owner_and_more'),
        ('assets', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accounttype',
            name='uniq_system_accounttype_slug',
        ),
        migrations.RemoveConstraint(
            model_name='accounttype',
            name='uniq_user_accounttype_name',
        ),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', False)), fields=('name', 'owner'), name='uniq_user_accounttype_name'),
        ),
    ]
