# Generated by Django 6.0.1 on 2026-01-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_accounttype_uniq_system_accounttype_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='allows_multiple',
        ),
    ]
