# Generated by Django 5.2.6 on 2025-09-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_classificationdefinition_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationdefinition',
            name='all_countries',
            field=models.BooleanField(default=False, help_text='If true, this classification applies globally (all countries).'),
        ),
        migrations.AlterField(
            model_name='classificationdefinition',
            name='jurisdictions',
            field=models.JSONField(blank=True, default=list, help_text="List of ISO country codes (e.g., ['US'], ['CA'], ['GB'])."),
        ),
    ]
