# Generated by Django 6.0 on 2025-12-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_account_type_alter_account_broker'),
        ('assets', '0008_exchange_delay_exchange_symbol_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=30, default=0, max_digits=50)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.asset')),
            ],
            options={
                'ordering': ['account', 'asset'],
                'unique_together': {('account', 'asset')},
            },
        ),
    ]
