# Generated by Django 6.0.1 on 2026-01-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_accounttype_allows_multiple'),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=30, default=0, help_text='Total quantity of this asset held in the account.', max_digits=50)),
                ('average_purchase_price', models.DecimalField(blank=True, decimal_places=30, help_text='Weighted average purchase price per unit.', max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.asset')),
            ],
            options={
                'ordering': ['account', 'asset'],
                'unique_together': {('account', 'asset')},
            },
        ),
    ]
