# Generated by Django 5.2.6 on 2025-09-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_classificationdefinition_all_countries_and_more'),
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='uniq_account_name_in_portfolio',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('portfolio', 'account_type', 'name'), name='uniq_account_name_in_portfolio_per_type'),
        ),
    ]
