# Generated by Django 6.0.1 on 2026-01-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_holding'),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='custom_reason',
            field=models.CharField(blank=True, choices=[('user', 'User initiated'), ('market', 'Market unavailable')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='original_ticker',
            field=models.CharField(blank=True, db_index=True, help_text='Ticker used when this holding was market-backed.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='source',
            field=models.CharField(choices=[('asset', 'Market Asset'), ('custom', 'Custom Asset')], default='asset', max_length=20),
        ),
        migrations.AlterField(
            model_name='holding',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='assets.asset'),
        ),
    ]
