# Generated by Django 6.0.1 on 2026-01-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_holding_custom_reason_holding_original_ticker_and_more'),
        ('assets', '0003_preciousmetalasset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'asset')), fields=('account', 'asset'), name='unique_account_asset_holding'),
        ),
    ]
