# Generated by Django 6.0.2 on 2026-02-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trusted_device_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trusteddevicetoken',
            new_name='users_trust_user_id_48e2ed_idx',
            old_name='users_trust_user_id_ebf8aa_idx',
        ),
        migrations.RenameIndex(
            model_name='trusteddevicetoken',
            new_name='users_trust_expires_9957f6_idx',
            old_name='users_trust_expires_a238c3_idx',
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='purpose',
            field=models.CharField(choices=[('verify_email', 'Verify Email'), ('login_security', 'Login Security')], default='verify_email', max_length=30),
        ),
    ]
