# Generated by Django 6.0.2 on 2026-02-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverificationtoken_target_email_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='users_email_user_id_aeb8f8_idx',
            old_name='users_evt_uptc_idx',
        ),
    ]
