# Generated by Django 5.2.3 on 2025-06-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profile_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
