# Generated by Django 5.1.6 on 2025-03-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual Account'), ('asset_manager', 'Asset Manager')], default='individual', max_length=20),
        ),
    ]
