# Generated by Django 5.1.6 on 2025-03-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='account_type',
        ),
    ]
