# Generated by Django 5.2.1 on 2025-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_language_alter_profile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='1995-10-07'),
            preserve_default=False,
        ),
    ]
