# Generated by Django 5.1.6 on 2025-03-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_role_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
    ]
