# Generated by Django 5.2.1 on 2025-05-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_timezone_alter_profile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
