# Generated by Django 5.2.1 on 2025-05-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_birth_date_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_setup_complete',
        ),
    ]
