# Generated by Django 5.2.5 on 2025-08-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier, e.g. 'pe_ratio', 'unrealized_gain'", max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('expression', models.TextField(help_text="Expression in terms of other formula keys, e.g. 'price / earnings'")),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 (whole numbers)'), (2, '2 (cents)'), (4, '4 (fx / crypto standard)'), (8, '8 (crypto max precision)')], help_text='User-specified precision; system formulas may use constraints', null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
