# Generated by Django 6.0.2 on 2026-02-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Human-readable formula name.', max_length=100)),
                ('identifier', models.SlugField(help_text='Stable snake_case identifier.', max_length=100)),
                ('expression', models.TextField(help_text='Python-style mathematical expression.')),
                ('dependencies', models.JSONField(default=list, editable=False, help_text='Derived identifiers referenced by this formula.')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, help_text='Optional precision override.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='FormulaDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(help_text='Semantic identifier (e.g. current_value).', max_length=100)),
                ('name', models.CharField(help_text='Display name.', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Optional description of this formula's meaning.")),
                ('dependency_policy', models.CharField(choices=[('auto_expand', 'Auto-expand dependencies'), ('strict', 'Strict (no auto-create)')], default='strict', help_text='How missing dependencies are handled.', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System-defined and analytics-safe.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
    ]
