# Generated by Django 6.0.1 on 2026-01-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_preciousmetalasset'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Human-readable formula name.', max_length=100)),
                ('identifier', models.SlugField(help_text='Stable snake_case identifier.', max_length=100)),
                ('expression', models.TextField(help_text='Python-style mathematical expression.')),
                ('dependencies', models.JSONField(default=list, editable=False, help_text='Derived identifiers referenced by this formula.')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, help_text='Optional precision override.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null = system formula, otherwise user-owned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='users.profile')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='FormulaDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(help_text='Semantic identifier (e.g. current_value).', max_length=100)),
                ('name', models.CharField(help_text='Display name.', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Optional description of this formula's meaning.")),
                ('dependency_policy', models.CharField(choices=[('auto_expand', 'Auto-expand dependencies'), ('strict', 'Strict (no auto-create)')], default='strict', help_text='How missing dependencies are handled.', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System-defined and analytics-safe.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_definitions', to='assets.assettype')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='formulas.formula')),
                ('owner', models.ForeignKey(blank=True, help_text='Null = system definition, otherwise user-owned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_definitions', to='users.profile')),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(fields=('identifier', 'owner'), name='uniq_formula_identifier_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='formuladefinition',
            constraint=models.UniqueConstraint(fields=('identifier', 'asset_type', 'owner'), name='uniq_formula_definition_per_asset_type_owner'),
        ),
    ]
