# Generated by Django 5.2.6 on 2025-09-08 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulas', '0001_initial'),
        ('schemas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formula',
            name='schema',
            field=models.ForeignKey(blank=True, help_text='If null, this is a global/system formula. Otherwise, scoped to schema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='schemas.schema'),
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('key',), name='unique_system_formula_key'),
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', False)), fields=('schema', 'key'), name='unique_schema_formula_key'),
        ),
    ]
