# Generated by Django 6.0.1 on 2026-01-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('formulas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null = system formula, otherwise user-owned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='users.profile'),
        ),
        migrations.AddField(
            model_name='formuladefinition',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_definitions', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='formuladefinition',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='formulas.formula'),
        ),
        migrations.AddField(
            model_name='formuladefinition',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Null = system definition, otherwise user-owned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_definitions', to='users.profile'),
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(fields=('identifier', 'owner'), name='uniq_formula_identifier_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='formuladefinition',
            constraint=models.UniqueConstraint(fields=('identifier', 'asset_type', 'owner'), name='uniq_formula_definition_per_asset_type_owner'),
        ),
    ]
