# Generated by Django 5.2.5 on 2025-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 (whole numbers)'), (2, '2 (cents)'), (4, '4 (fx/crypto standard)'), (8, '8 (crypto max precision)')], help_text='Explicit precision for calculated results', null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, help_text='List of source_fields this formula depends on'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='expression',
            field=models.TextField(help_text="Expression using other column source_fields, e.g. '(price - purchase_price) * quantity'"),
        ),
        migrations.AlterField(
            model_name='formula',
            name='key',
            field=models.SlugField(help_text="Stable identifier for this formula, e.g. 'pe_ratio', 'unrealized_gain'", max_length=100, unique=True),
        ),
    ]
