# Generated by Django 5.2.5 on 2025-09-03 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_alter_formula_decimal_places_and_more'),
        ('schemas', '0004_schemacolumn_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='schema',
            field=models.ForeignKey(blank=True, help_text='If null, this is a global/system formula. Otherwise, scoped to schema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='schemas.schema'),
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('key',), name='unique_system_formula_key'),
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', False)), fields=('schema', 'key'), name='unique_schema_formula_key'),
        ),
    ]
