# Generated by Django 5.2.5 on 2025-09-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_formula_schema_formula_unique_system_formula_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='key',
            field=models.SlugField(help_text="Stable identifier for this formula, e.g. 'pe_ratio', 'unrealized_gain'", max_length=100),
        ),
    ]
