# Generated by Django 5.2.6 on 2025-09-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('formulas', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('stock_self', 'Self-Managed Stock'), ('stock_managed', 'Managed Stock'), ('crypto_wallet', 'Crypto Wallet'), ('metal_storage', 'Metal Storage'), ('custom', 'Custom Account')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('schema_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subportfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='portfolios.subportfolio')),
            ],
            options={
                'unique_together': {('subportfolio', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='SchemaColumnTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(help_text='AccountType this template applies to (e.g., stock_self, crypto_wallet).', max_length=50)),
                ('source', models.CharField(choices=[('asset', 'Asset'), ('holding', 'Holding'), ('calculated', 'Calculated'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, help_text="Stable identifier in snake_case, e.g. 'price', 'purchase_price'", max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('decimal', 'Number'), ('string', 'Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('url', 'URL')], max_length=20)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(blank=True, help_text='If this is a calculated column, link to the formula', null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulas.formula')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('account_type', 'source_field', 'source')},
            },
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('identifier', models.SlugField(help_text='Stable internal key used for referencing this column in formulas. Auto-generated for custom columns.', max_length=100)),
                ('data_type', models.CharField(choices=[('decimal', 'Number'), ('string', 'Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('url', 'URL')], max_length=20)),
                ('source', models.CharField(choices=[('asset', 'Asset'), ('holding', 'Holding'), ('calculated', 'Calculated'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, max_length=100, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Whether this is a system default column')),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(blank=True, help_text='Direct formula if this is a custom calculated column', null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulas.formula')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.schema')),
                ('template', models.ForeignKey(blank=True, help_text='Template this column was created from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schemas.schemacolumntemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='schemas.schemacolumn')),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema_values', to='assets.holding')),
            ],
            options={
                'unique_together': {('column', 'holding')},
            },
        ),
        migrations.CreateModel(
            name='SchemaColumnVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_settings', to='schemas.schemacolumn')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('column', 'content_type', 'object_id')},
            },
        ),
    ]
