# Generated by Django 5.2.4 on 2025-07-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schema_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('decimal', 'Decimal'), ('integer', 'Integer'), ('string', 'Text'), ('date', 'Date'), ('url', 'URL')], max_length=20)),
                ('source', models.CharField(choices=[('asset', 'Asset'), ('holding', 'Holding'), ('calculated', 'Calculated'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, max_length=100, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.schema')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveIntegerField()),
                ('value', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('account_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='schemas.schemacolumn')),
            ],
            options={
                'unique_together': {('column', 'account_ct', 'account_id')},
            },
        ),
    ]
