# Generated by Django 5.2.8 on 2025-11-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('key', models.SlugField(help_text='Stable formula key (auto-normalized to snake_case).', max_length=100)),
                ('expression', models.TextField(help_text='Formula expression using column identifiers.')),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='Identifiers of SchemaColumns that this formula depends on.')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, help_text='If set, overrides SchemaColumn constraints for result precision.', null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schema Formula',
                'verbose_name_plural': 'Schema Formulas',
            },
        ),
        migrations.CreateModel(
            name='SchemaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(db_index=True, help_text='Account type this template applies to (e.g., equity_self, crypto_wallet).', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable template name.', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_type'],
            },
        ),
        migrations.CreateModel(
            name='MasterConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('applies_to', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], db_index=True, max_length=20)),
                ('default_value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('max_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['applies_to', 'label'],
                'unique_together': {('applies_to', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('equity_self', 'Brokerage Account'), ('crypto_wallet', 'Crypto Wallet'), ('metal_storage', 'Precious Metals Account'), ('bond_broker', 'Bond Brokerage Account'), ('bond_trust', 'Bond Trust Account'), ('real_estate', 'Real Estate Holding'), ('custom', 'Custom Account')], db_index=True, help_text='Specific account type this schema applies to (e.g., equity_self, crypto_wallet).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['account_type'],
                'unique_together': {('portfolio', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], max_length=20)),
                ('source', models.CharField(choices=[('holding', 'Holding'), ('asset', 'Asset'), ('formula', 'Formula'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, max_length=100, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('display_order', models.PositiveBigIntegerField(default=0)),
                ('formula', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column', to='schemas.formula')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.schema')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('schema', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='SchemaColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='schemas.schemacolumn')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_values', to='assets.holding')),
            ],
            options={
                'unique_together': {('column', 'holding')},
            },
        ),
        migrations.CreateModel(
            name='SchemaConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('max_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('applies_to', models.CharField(blank=True, choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], max_length=20, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints_set', to='schemas.schemacolumn')),
            ],
            options={
                'unique_together': {('column', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchemaTemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], max_length=20)),
                ('source', models.CharField(choices=[('holding', 'Holding'), ('asset', 'Asset'), ('formula', 'Formula'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, max_length=100, null=True)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False, help_text='If True, this column will appear automatically when a schema is generated.')),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.schematemplate')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('template', 'identifier')},
            },
        ),
    ]
