# Generated by Django 5.2.6 on 2025-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='domain_type',
            field=models.CharField(choices=[('equity', 'Equities'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('bond', 'Bonds'), ('real_estate', 'Real Estate'), ('custom', 'Custom')], db_index=True, max_length=20),
        ),
    ]
