# Generated by Django 6.0 on 2025-12-05 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_account_type_alter_account_broker'),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['account_type__slug']},
        ),
        migrations.AlterModelOptions(
            name='schematemplate',
            options={'ordering': ['account_type__slug']},
        ),
        migrations.AlterField(
            model_name='schema',
            name='account_type',
            field=models.ForeignKey(help_text='AccountType this schema applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='accounts.accounttype'),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='columns', to='schemas.formula'),
        ),
        migrations.AlterField(
            model_name='schematemplate',
            name='account_type',
            field=models.OneToOneField(help_text='AccountType this template applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='schema_template', to='accounts.accounttype'),
        ),
        migrations.AlterField(
            model_name='schematemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schematemplatecolumn',
            name='formula',
            field=models.ForeignKey(blank=True, help_text="Formula to use when source='formula'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_columns', to='schemas.formula'),
        ),
        migrations.AlterField(
            model_name='schematemplatecolumn',
            name='source_field',
            field=models.CharField(blank=True, help_text='Holding/Asset field name OR unused when formula is provided.', max_length=100, null=True),
        ),
    ]
