# Generated by Django 5.2.6 on 2025-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schemacolumntemplate',
            unique_together={('account_type', 'source_field', 'source')},
        ),
        migrations.AlterField(
            model_name='schemacolumntemplate',
            name='account_type',
            field=models.CharField(help_text='AccountType this template applies to (e.g., stock_self, crypto_wallet).', max_length=50),
        ),
        migrations.AlterField(
            model_name='schemacolumntemplate',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemacolumntemplate',
            name='source_field',
            field=models.CharField(blank=True, help_text="Stable identifier in snake_case, e.g. 'price', 'purchase_price'", max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='schemacolumntemplate',
            name='schema_type',
        ),
    ]
