# Generated by Django 5.2.7 on 2025-11-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(db_index=True, help_text='Account type this template applies to (e.g., equity_self, crypto_wallet).', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable template name.', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_type'],
            },
        ),
        migrations.CreateModel(
            name='SchemaTemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], max_length=20)),
                ('source', models.CharField(choices=[('holding', 'Holding'), ('asset', 'Asset'), ('formula', 'Formula'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, max_length=100, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False, help_text='If True, this column will appear automatically when a schema is generated.')),
                ('default_constraints', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.schematemplate')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('template', 'identifier')},
            },
        ),
    ]
