# Generated by Django 5.2.5 on 2025-08-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemacolumntemplate',
            old_name='editable',
            new_name='is_editable',
        ),
    ]
