# Generated by Django 5.2.6 on 2025-09-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schemacolumnvalue',
            name='unique_scv_holding',
        ),
    ]
