# Generated by Django 5.2.5 on 2025-08-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_preciousmetalholding_investment_theme_and_more'),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='formula',
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='custom_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='field_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='formula_method',
            field=models.CharField(blank=True, help_text='Backend Python method to evaluate this column', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='investment_theme',
            field=models.ForeignKey(blank=True, help_text='If this column represents a custom theme, link it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.investmenttheme'),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='data_type',
            field=models.CharField(choices=[('decimal', 'Decimal'), ('integer', 'Integer'), ('string', 'Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('url', 'URL')], max_length=20),
        ),
    ]
