# Generated by Django 5.2.7 on 2025-10-23 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('applies_to', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], db_index=True, max_length=20)),
                ('default_value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('max_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['applies_to', 'label'],
                'unique_together': {('applies_to', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchemaConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('min_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('max_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('applies_to', models.CharField(blank=True, choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], max_length=20, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints_set', to='schemas.schemacolumn')),
            ],
            options={
                'unique_together': {('column', 'name')},
            },
        ),
    ]
