# Generated by Django 5.2.5 on 2025-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemacolumntemplate',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterUniqueTogether(
            name='schemacolumntemplate',
            unique_together={('account_model_ct', 'schema_type', 'source_field')},
        ),
        migrations.AlterField(
            model_name='schemacolumntemplate',
            name='source_field',
            field=models.CharField(blank=True, help_text="Stable identifier in snake_case, e.g. 'price', 'purchase_price', 'unrealized_gain'", max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='schemacolumntemplate',
            name='template_key',
        ),
    ]
