# Generated by Django 5.2.6 on 2025-09-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='template',
        ),
        migrations.DeleteModel(
            name='SchemaColumnTemplate',
        ),
    ]
