# Generated by Django 5.2.4 on 2025-07-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Whether this is a system default column'),
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='scope',
            field=models.CharField(choices=[('portfolio', 'Portfolio-wide'), ('subportfolio', 'Subportfolio-wide'), ('account', 'Account-specific')], default='subportfolio', max_length=20),
        ),
        migrations.CreateModel(
            name='SchemaColumnVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_settings', to='schemas.schemacolumn')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('column', 'content_type', 'object_id')},
            },
        ),
    ]
