# Generated by Django 5.2.7 on 2025-10-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='is_deletable',
            field=models.BooleanField(default=True),
        ),
    ]
