# Generated by Django 5.2.8 on 2025-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematemplatecolumn',
            name='constraints',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
