# Generated by Django 5.2.8 on 2025-11-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula',
            old_name='key',
            new_name='identifier',
        ),
    ]
