# Generated by Django 5.2.8 on 2025-11-21 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_initial'),
        ('schemas', '0002_schematemplatecolumn_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='formula',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column', to='formulas.formula'),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('key', models.SlugField(help_text='Stable formula key (auto-normalized to snake_case).', max_length=100)),
                ('expression', models.TextField(help_text='Formula expression using column identifiers.')),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='Identifiers of SchemaColumns that this formula depends on.')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, help_text='If set, overrides SchemaColumn constraints for result precision.', null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schema Formula',
                'verbose_name_plural': 'Schema Formulas',
                'constraints': [models.UniqueConstraint(fields=('column',), name='unique_formula_per_column')],
            },
        ),
    ]
