# Generated by Django 6.0 on 2025-12-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_holding'),
        ('schemas', '0002_alter_schema_options_alter_schematemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumnvalue',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_values', to='accounts.holding'),
        ),
    ]
