# Generated by Django 5.2.4 on 2025-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_schemacolumn_is_system_schemacolumn_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='formula_expression',
            field=models.TextField(blank=True, help_text="User-defined formula like '(quantity * price) / pe_ratio' -> something that wont be in the backend.", null=True),
        ),
    ]
