# Generated by Django 5.2.5 on 2025-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_remove_schemacolumn_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='structure_edit_mode',
            field=models.CharField(choices=[('full', 'Full'), ('decimal_only', 'Decimal only'), ('locked', 'Locked')], default='locked', max_length=20),
        ),
    ]
