# Generated by Django 5.2.6 on 2025-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_remove_schemacolumn_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='account_type',
            field=models.CharField(choices=[('stock', 'Stocks'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schema',
            name='schema_type',
            field=models.CharField(choices=[('stock', 'Stocks'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('custom', 'Custom')], max_length=20),
        ),
    ]
