# Generated by Django 5.2.8 on 2025-11-21 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_rename_key_formula_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaFormulaTemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_columns', to='schemas.formula')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_columns', to='schemas.schematemplate')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('template', 'identifier')},
            },
        ),
    ]
