# Generated by Django 5.2.7 on 2025-10-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_masterconstraint_schemaconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterconstraint',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
