# Generated by Django 5.2.7 on 2025-11-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_schematemplate_schematemplatecolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schematemplatecolumn',
            name='default_constraints',
        ),
        migrations.AlterField(
            model_name='schematemplatecolumn',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
