# Generated by Django 6.0.1 on 2026-01-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_alter_schemacolumntemplatebehaviour_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumntemplatebehaviour',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviours', to='schemas.schemacolumntemplate'),
        ),
    ]
