# Generated by Django 5.2.5 on 2025-09-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_alter_schemacolumntemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='identifier',
        ),
    ]
