# Generated by Django 5.2.5 on 2025-08-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_rename_editable_schemacolumntemplate_is_editable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemacolumn',
            old_name='editable',
            new_name='is_editable',
        ),
    ]
