# Generated by Django 5.2.5 on 2025-08-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_preciousmetalholding_investment_theme_and_more'),
        ('schemas', '0003_schemacolumn_structure_edit_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='decimal_places',
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='constraints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SchemaColumnTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('asset', 'Asset'), ('holding', 'Holding'), ('calculated', 'Calculated'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('decimal', 'Decimal'), ('integer', 'Integer'), ('string', 'Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('url', 'URL')], max_length=20)),
                ('field_path', models.CharField(blank=True, max_length=255, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('formula_expression', models.TextField(blank=True, null=True)),
                ('formula_method', models.CharField(blank=True, max_length=100, null=True)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment_theme', models.ForeignKey(blank=True, help_text='If this column represents a custom theme, link it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.investmenttheme')),
            ],
            options={
                'verbose_name': 'Schema Column Template',
                'verbose_name_plural': 'Schema Column Templates',
                'ordering': ['display_order'],
                'unique_together': {('asset_type', 'source', 'source_field')},
            },
        ),
    ]
