# Generated by Django 5.2.4 on 2025-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_schemacolumn_formula_expression'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAssetSchemaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=100, unique=True)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Schema Config',
                'verbose_name_plural': 'Asset Schema Configs',
            },
        ),
    ]
