# Generated by Django 5.2.5 on 2025-08-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_rename_editable_schemacolumn_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this a default column from the template config?'),
        ),
    ]
