# Generated by Django 5.2.5 on 2025-09-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_remove_schemacolumn_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='identifier',
            field=models.SlugField(blank=True, help_text='Stable internal key used for referencing this column in formulas. Auto-generated for custom columns.', max_length=100, null=True),
        ),
    ]
