# Generated by Django 6.0.1 on 2026-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_alter_schemacolumntemplatebehaviour_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaColumnCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(help_text="Stable system identifier (e.g. 'valuation', 'cash_flow').", unique=True)),
                ('name', models.CharField(help_text="Human-readable category name (e.g. 'Valuation').", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description for UI/tooltips.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls ordering in UI lists.')),
                ('is_system', models.BooleanField(default=False, help_text='System categories cannot be deleted or renamed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
