# Generated by Django 5.2.8 on 2025-11-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_delete_schemaformulatemplatecolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematemplatecolumn',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_columns', to='schemas.formula'),
        ),
        migrations.AlterField(
            model_name='schematemplatecolumn',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
