# Generated by Django 5.2.5 on 2025-08-25 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_schemacolumn_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='scope',
        ),
    ]
