# Generated by Django 6.0.1 on 2026-01-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('schemas', '0004_schemacolumncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumntemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Semantic category used for UI grouping.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='schemas.schemacolumncategory'),
        ),
        migrations.CreateModel(
            name='AccountColumnVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_visibility', to='accounts.account')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_visibility', to='schemas.schemacolumn')),
            ],
            options={
                'unique_together': {('account', 'column')},
            },
        ),
    ]
