# Generated by Django 5.2.5 on 2025-08-19 01:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schemas', '0004_remove_schemacolumn_decimal_places_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemacolumntemplate',
            old_name='asset_type',
            new_name='schema_type',
        ),
        migrations.AlterUniqueTogether(
            name='schemacolumntemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schemacolumntemplate',
            name='account_model_ct',
            field=models.ForeignKey(default=datetime.datetime(2025, 8, 19, 1, 17, 3, 930357, tzinfo=datetime.timezone.utc), help_text='The account model this template applies to.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schemacolumntemplate',
            unique_together={('account_model_ct', 'source', 'source_field')},
        ),
        migrations.CreateModel(
            name='SubPortfolioSchemaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subportfolio_id', models.PositiveIntegerField()),
                ('account_model_id', models.PositiveIntegerField(blank=True, null=True)),
                ('account_model_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
                ('subportfolio_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('subportfolio_ct', 'subportfolio_id', 'account_model_ct')},
            },
        ),
    ]
