# Generated by Django 5.2.6 on 2025-09-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_schemacolumn_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='field_path',
        ),
    ]
