# Generated by Django 6.0.1 on 2026-01-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_schemacolumntemplate_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumntemplate',
            name='constraint_overrides',
            field=models.JSONField(blank=True, help_text='Constraint overrides applied when this template is expanded into a schema column.', null=True),
        ),
    ]
