# Generated by Django 5.2.8 on 2025-11-25 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_schematemplatecolumn_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column', to='schemas.formula'),
        ),
    ]
