# Generated by Django 5.2.5 on 2025-08-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_remove_schemacolumn_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='structure_edit_mode',
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='formula_expression',
            field=models.TextField(blank=True, help_text="User-defined formula like '(quantity * price) / pe_ratio' -> something that won't be in the backend.", null=True),
        ),
    ]
