# Generated by Django 5.2.6 on 2025-09-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_remove_schemacolumn_field_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAssetSchemaConfig',
        ),
    ]
