# Generated by Django 5.2.5 on 2025-08-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_remove_schemacolumn_structure_edit_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='is_default',
        ),
    ]
