# Generated by Django 5.2.6 on 2025-09-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_delete_customassetschemaconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumntemplate',
            name='field_path',
        ),
    ]
