# Generated by Django 6.0.1 on 2026-02-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_schemacolumntemplate_constraint_overrides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterconstraint',
            name='default_integer',
        ),
        migrations.RemoveField(
            model_name='masterconstraint',
            name='max_integer',
        ),
        migrations.RemoveField(
            model_name='masterconstraint',
            name='min_integer',
        ),
        migrations.RemoveField(
            model_name='schemaconstraint',
            name='max_integer',
        ),
        migrations.RemoveField(
            model_name='schemaconstraint',
            name='min_integer',
        ),
        migrations.RemoveField(
            model_name='schemaconstraint',
            name='value_integer',
        ),
        migrations.AddField(
            model_name='masterconstraint',
            name='default_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterconstraint',
            name='default_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterconstraint',
            name='max_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterconstraint',
            name='min_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemaconstraint',
            name='max_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemaconstraint',
            name='min_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemaconstraint',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemaconstraint',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterconstraint',
            name='applies_to',
            field=models.CharField(choices=[('decimal', 'Number'), ('string', 'String'), ('percent', 'Percent'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='data_type',
            field=models.CharField(choices=[('decimal', 'Number'), ('percent', 'Percent'), ('string', 'String'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schemacolumntemplate',
            name='data_type',
            field=models.CharField(choices=[('decimal', 'Number'), ('percent', 'Percent'), ('string', 'String'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schemaconstraint',
            name='applies_to',
            field=models.CharField(choices=[('decimal', 'Number'), ('string', 'String'), ('percent', 'Percent'), ('boolean', 'Boolean'), ('date', 'Date')], max_length=20),
        ),
    ]
