# Generated by Django 5.2.5 on 2025-08-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_remove_schemacolumn_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='investment_theme',
        ),
    ]
