# Generated by Django 5.2.6 on 2025-09-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_remove_schemacolumntemplate_field_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='identifier',
            field=models.SlugField(default='h', help_text='Stable internal key used for referencing this column in formulas. Auto-generated for custom columns.', max_length=100),
            preserve_default=False,
        ),
    ]
