# Generated by Django 6.0.1 on 2026-02-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_remove_masterconstraint_default_integer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemacolumnvalue',
            options={'ordering': ('column__identifier',)},
        ),
    ]
