# Generated by Django 5.2.5 on 2025-08-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schemas', '0008_remove_schemacolumn_investment_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='formula_method',
        ),
        migrations.AlterUniqueTogether(
            name='schemacolumntemplate',
            unique_together={('account_model_ct', 'source', 'source_field', 'template_key')},
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='identifier',
            field=models.SlugField(default='s', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemacolumntemplate',
            name='template_key',
            field=models.SlugField(default='s', help_text="Stable key for formulas, e.g. 'earnings', 'price_to_book'", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='data_type',
            field=models.CharField(choices=[('decimal', 'Number'), ('string', 'Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('url', 'URL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schemacolumntemplate',
            name='data_type',
            field=models.CharField(choices=[('decimal', 'Number'), ('string', 'Text'), ('date', 'Date'), ('datetime', 'Datetime'), ('time', 'Time'), ('url', 'URL')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='schemacolumntemplate',
            name='formula_method',
        ),
    ]
