# Generated by Django 6.0.1 on 2026-02-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_alter_schemacolumnvalue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemacolumnvalue',
            options={},
        ),
    ]
