# Generated by Django 5.2.6 on 2025-09-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_alter_schemacolumn_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumntemplate',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, help_text='Optional order hint. Will be applied if column is created as default.', null=True),
        ),
    ]
