# Generated by Django 6.0.3 on 2026-04-03 17:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('users', '0002_remove_profile_country_code_authevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Portfolio', max_length=100)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('spouse', 'Spouse'), ('family', 'Family'), ('other', 'Other')], default='personal', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='users.profile')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(blank=True, help_text='Optional user-defined category, such as Brokerage, Private Equity, Funds, Wallet, Garage, or Vault.', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Optional short explanation for what this container represents.', max_length=255)),
                ('is_tracked', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, help_text='Optional external source for this container, such as Plaid.', max_length=50)),
                ('external_id', models.CharField(blank=True, help_text='Optional external account identifier for tracked containers.', max_length=255)),
                ('external_parent_id', models.CharField(blank=True, help_text='Optional external connection identifier for tracked containers.', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='holdings.portfolio')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=18, default=Decimal('1'), help_text='Number of units held. Use 1 for directly valued holdings when appropriate.', max_digits=40)),
                ('unit_value', models.DecimalField(blank=True, decimal_places=18, help_text='Current value per unit for this holding.', max_digits=40, null=True)),
                ('unit_cost_basis', models.DecimalField(blank=True, decimal_places=18, help_text='Optional cost basis per unit.', max_digits=40, null=True)),
                ('notes', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Flexible holding-specific metadata and overrides.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.asset')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='holdings.container')),
            ],
            options={
                'ordering': ['container', 'asset', 'id'],
                'indexes': [models.Index(fields=['container', 'asset'], name='holdings_ho_contain_f82227_idx'), models.Index(fields=['asset'], name='holdings_ho_asset_i_929199_idx')],
                'constraints': [models.UniqueConstraint(fields=('container', 'asset'), name='uniq_holding_per_container_asset')],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['profile', 'is_default'], name='holdings_po_profile_7a7a04_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['profile', 'kind'], name='holdings_po_profile_52cf6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='uniq_portfolio_name_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('profile',), name='uniq_default_portfolio_per_profile'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['portfolio', 'kind'], name='holdings_co_portfol_09baca_idx'),
        ),
        migrations.AddConstraint(
            model_name='container',
            constraint=models.UniqueConstraint(fields=('portfolio', 'name'), name='uniq_container_name_per_portfolio'),
        ),
    ]
