# Generated by Django 6.0.3 on 2026-04-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingFactDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('decimal', 'Decimal'), ('percent', 'Percent'), ('string', 'String'), ('boolean', 'Boolean'), ('date', 'Date'), ('json', 'JSON')], default='string', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_fact_definitions', to='holdings.portfolio')),
            ],
            options={
                'ordering': ['label', 'key'],
            },
        ),
        migrations.CreateModel(
            name='HoldingFactValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='holdings.holdingfactdefinition')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_values', to='holdings.holding')),
            ],
            options={
                'ordering': ['definition__label', 'definition__key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HoldingOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('data_type', models.CharField(choices=[('decimal', 'Decimal'), ('percent', 'Percent'), ('string', 'String'), ('boolean', 'Boolean'), ('date', 'Date'), ('json', 'JSON')], default='string', max_length=20)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='holdings.holding')),
            ],
            options={
                'ordering': ['key', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='holdingfactdefinition',
            index=models.Index(fields=['portfolio', 'is_active'], name='holdings_ho_portfol_a61251_idx'),
        ),
        migrations.AddConstraint(
            model_name='holdingfactdefinition',
            constraint=models.UniqueConstraint(fields=('portfolio', 'key'), name='uniq_holding_fact_definition_per_portfolio'),
        ),
        migrations.AddIndex(
            model_name='holdingfactvalue',
            index=models.Index(fields=['holding', 'definition'], name='holdings_ho_holding_ace87a_idx'),
        ),
        migrations.AddConstraint(
            model_name='holdingfactvalue',
            constraint=models.UniqueConstraint(fields=('holding', 'definition'), name='uniq_holding_fact_value_per_definition'),
        ),
        migrations.AddIndex(
            model_name='holdingoverride',
            index=models.Index(fields=['holding', 'key'], name='holdings_ho_holding_1a9903_idx'),
        ),
        migrations.AddConstraint(
            model_name='holdingoverride',
            constraint=models.UniqueConstraint(fields=('holding', 'key'), name='uniq_holding_override_per_key'),
        ),
    ]
