# Generated by Django 6.0.3 on 2026-04-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_holdingfactdefinition_holdingfactvalue_and_more'),
        ('users', '0003_profile_country_supportedcountry_supportedcurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayoutState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=80)),
                ('active_layout_id', models.CharField(blank=True, max_length=120)),
                ('layouts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout_states', to='users.profile')),
            ],
            options={
                'ordering': ['scope'],
                'indexes': [models.Index(fields=['profile', 'scope'], name='holdings_da_profile_91d7ef_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'scope'), name='uniq_dashboard_layout_state_per_profile_scope')],
            },
        ),
    ]
