# Generated by Django 6.0 on 2025-12-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0002_alter_schema_options_alter_schematemplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('supports_length', models.BooleanField(default=False)),
                ('supports_decimals', models.BooleanField(default=False)),
                ('supports_numeric_limits', models.BooleanField(default=False)),
                ('supports_regex', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ConstraintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=True)),
                ('applies_to', models.ManyToManyField(blank=True, related_name='allowed_constraint_types', to='datatype.datatype')),
                ('value_data_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constraint_value_types', to='datatype.datatype')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='AppliedConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('is_user_defined', models.BooleanField(default=False)),
                ('schema_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_constraints', to='schemas.schemacolumn')),
                ('constraint_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_constraints', to='datatype.constrainttype')),
            ],
            options={
                'unique_together': {('schema_column', 'constraint_type')},
            },
        ),
        migrations.CreateModel(
            name='ConstraintDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.TextField(blank=True, help_text='System-level default value for this constraint.', null=True)),
                ('allow_user_override', models.BooleanField(default=False, help_text='Whether user or custom assets can override this constraint.')),
                ('is_system', models.BooleanField(default=True)),
                ('constraint_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_definitions', to='datatype.constrainttype')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_constraints', to='datatype.datatype')),
            ],
            options={
                'ordering': ['data_type__slug', 'constraint_type__slug'],
                'unique_together': {('data_type', 'constraint_type')},
            },
        ),
    ]
