# Generated by Django 5.2.3 on 2025-06-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('assets', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='investment_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='portfolios.investmenttheme'),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='self_managed_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to='accounts.selfmanagedaccount'),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to='assets.stock'),
        ),
        migrations.AddIndex(
            model_name='stockholding',
            index=models.Index(fields=['self_managed_account'], name='assets_stoc_self_ma_aad51b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockholding',
            index=models.Index(fields=['stock'], name='assets_stoc_stock_i_44c9e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockholding',
            constraint=models.UniqueConstraint(fields=('self_managed_account', 'stock'), name='unique_holding_per_account'),
        ),
    ]
