# Generated by Django 5.2.3 on 2025-06-24 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('core', '0002_fxrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtags', to='assets.investmenttheme')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tags', to='core.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='investment_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='assets.investmenttheme'),
        ),
    ]
