# Generated by Django 5.1.7 on 2025-03-11 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dividends', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('is_etf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('self_managed', 'Self Managed'), ('managed', 'Managed')], default='self_managed', max_length=20)),
                ('account_name', models.CharField(default='Stock Account', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_columns', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Stock Account',
                'verbose_name_plural': 'Stock Accounts',
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.stock')),
                ('stock_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.stockaccount')),
            ],
            options={
                'unique_together': {('stock_account', 'stock')},
            },
        ),
        migrations.AddField(
            model_name='stockaccount',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='stock_accounts', through='securities.StockHolding', to='securities.stock'),
        ),
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Stock Portfolio', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_columns', models.JSONField(blank=True, default=dict)),
                ('individual_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolios', to='portfolio.individualportfolio')),
            ],
        ),
        migrations.AddField(
            model_name='stockaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_accounts', to='securities.stockportfolio'),
        ),
        migrations.CreateModel(
            name='StockTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tags', to='securities.stocktag')),
                ('stock_holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_tags', to='securities.stockholding')),
            ],
        ),
    ]
