# Generated by Django 5.1.6 on 2025-03-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0003_individualportfolio_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('self_managed', 'Self Managed'), ('managed', 'Managed')], default='self_managed', max_length=20)),
                ('account_name', models.CharField(default='Stock Portfolio', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolio', to='portfolio.individualportfolio')),
            ],
            options={
                'verbose_name': 'Stock Portfolio',
                'verbose_name_plural': 'Stock Portfolios',
            },
        ),
    ]
