# Generated by Django 5.1.7 on 2025-03-31 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockholding',
            old_name='custom_data',
            new_name='holding_display',
        ),
    ]
