# Generated by Django 5.1.7 on 2025-03-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockholding',
            unique_together={('stock_account', 'stock')},
        ),
    ]
