# Generated by Django 5.1.6 on 2025-03-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockaccount',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='stocktag',
            name='profile',
        ),
    ]
