# Generated by Django 5.1.7 on 2025-03-12 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='individual_portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolios', to='portfolio.individualportfolio'),
        ),
    ]
