# Generated by Django 5.1.7 on 2025-03-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_alter_stockholding_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stockaccount',
            name='custom_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
