# Generated by Django 5.1.7 on 2025-03-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_alter_stockportfolio_individual_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockaccount',
            options={},
        ),
        migrations.RemoveField(
            model_name='stockaccount',
            name='custom_columns',
        ),
    ]
