# Generated by Django 5.1.7 on 2025-04-18 14:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_rename_stock_exchange_stock_exchange_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schemacolumn',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stockportfolioschema',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockportfolioschema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='securities.stock'),
        ),
        migrations.DeleteModel(
            name='StockTag',
        ),
        migrations.RemoveField(
            model_name='stockportfolioschema',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stockportfolioschema',
            name='is_deletable',
        ),
    ]
