# Generated by Django 5.1.6 on 2025-03-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_remove_stockaccount_tags_remove_stocktag_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tags', to='securities.stocktag'),
        ),
    ]
