# Generated by Django 5.1.7 on 2025-04-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_rename_custom_data_stockholding_holding_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockportfolio',
            old_name='custom_columns',
            new_name='holding_display',
        ),
    ]
