# Generated by Django 5.1.6 on 2025-03-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_stocktag_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockaccount',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='stock_accounts', to='securities.stock'),
        ),
    ]
