# Generated by Django 5.1.7 on 2025-03-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('securities', '0003_alter_stockaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='dividends',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='individual_portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolio', to='portfolio.individualportfolio'),
        ),
    ]
