# Generated by Django 5.1.7 on 2025-04-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_alter_schemacolumn_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='column_type',
            field=models.CharField(choices=[('custom', 'Custom Input'), ('stock_info', 'Stock Information'), ('holding_info', 'Holding Information'), ('calculated', 'Calculated')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='schemacolumn',
            name='is_deletable',
            field=models.BooleanField(default=True),
        ),
    ]
