# Generated by Django 5.1.7 on 2025-03-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_remove_stock_dividends_remove_stock_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockportfolio',
            name='custom_columns',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='name',
        ),
    ]
