# Generated by Django 5.1.7 on 2025-03-11 01:40

from django.db import migrations


def migrate_tags(apps, schema_editor):
    StockTag = apps.get_model('securities', 'StockTag')
    StockHolding = apps.get_model('securities', 'StockHolding')

    for tag in StockTag.objects.all():
        if tag.stock_account:  # Assuming stock_account still exists in historical data
            # Find a StockHolding for this StockAccount (e.g., first one)
            holding = StockHolding.objects.filter(
                stock_account=tag.stock_account).first()
            if holding:
                tag.stock_holding = holding
                tag.save()


def reverse_migrate_tags(apps, schema_editor):
    StockTag = apps.get_model('securities', 'StockTag')
    for tag in StockTag.objects.all():
        tag.stock_holding = None
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_remove_stocktag_stock_account_stocktag_stock_holding'),
    ]

    operations = [
        migrations.RunPython(migrate_tags, reverse_migrate_tags),
    ]
