# Generated by Django 5.1.7 on 2025-04-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_schemacolumn_column_type_schemacolumn_is_deletable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemacolumn',
            name='value_type',
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='column_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('stock', 'Stock Info'), ('holding', 'Holding Info'), ('calculated', 'Calculated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
