# Generated by Django 5.2 on 2025-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_remove_schemacolumn_value_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='value_type',
            field=models.CharField(default='text', max_length=50),
            preserve_default=False,
        ),
    ]
