# Generated by Django 5.1.7 on 2025-03-14 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_individualportfolio_profile_portfolio'),
        ('securities', '0005_remove_stockportfolio_custom_columns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='individual_portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolio', to='portfolio.portfolio'),
        ),
    ]
