# Generated by Django 5.1.7 on 2025-03-11 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_migrate_stock_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktag',
            name='stock_holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_tags', to='securities.stockholding'),
        ),
    ]
