# Generated by Django 5.1.7 on 2025-03-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0006_alter_stockportfolio_individual_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockportfolio',
            old_name='individual_portfolio',
            new_name='portfolio',
        ),
    ]
