# Generated by Django 5.1.7 on 2025-03-18 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0007_rename_individual_portfolio_stockportfolio_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfManagedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='Self Managed Account', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_managed_accounts', to='securities.stockportfolio')),
                ('stocks', models.ManyToManyField(blank=True, related_name='self_managed_accounts', through='securities.StockHolding', to='securities.stock')),
            ],
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='stock_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.selfmanagedaccount'),
        ),
        migrations.DeleteModel(
            name='StockAccount',
        ),
    ]
