# Generated by Django 5.1.7 on 2025-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0007_stock_dividends_stock_last_updated_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_etf',
            field=models.BooleanField(default=False),
        ),
    ]
