# Generated by Django 5.1.7 on 2025-03-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0008_selfmanagedaccount_alter_stockholding_stock_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolio',
            name='custom_columns',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
