# Generated by Django 5.1.7 on 2025-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0009_stockportfolio_custom_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dividend_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_not_in_database',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
