# Generated by Django 5.1.7 on 2025-03-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0010_stock_dividend_rate_stock_is_not_in_database_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
