# Generated by Django 5.1.7 on 2025-03-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0011_stockholding_custom_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockholding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='custom_ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockholding',
            unique_together={('stock_account', 'stock', 'custom_ticker')},
        ),
    ]
