# Generated by Django 5.1.7 on 2025-03-28 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0013_alter_stockholding_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='stockholding',
            name='unique_stock_per_account',
        ),
        migrations.RemoveConstraint(
            model_name='stockholding',
            name='unique_custom_ticker_per_account',
        ),
        migrations.AlterUniqueTogether(
            name='stockholding',
            unique_together={('stock_account', 'stock', 'custom_ticker')},
        ),
        migrations.AddField(
            model_name='customstockholding',
            name='stock_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securities.selfmanagedaccount'),
        ),
        migrations.AlterUniqueTogether(
            name='customstockholding',
            unique_together={('stock_account', 'ticker')},
        ),
    ]
