# Generated by Django 6.0.2 on 2026-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_identifier', models.SlugField(help_text='Analytics dimension name (slug).', max_length=100)),
                ('source_analytic_name', models.SlugField(blank=True, help_text='Optional analytics name to disambiguate dimension source.', max_length=100, null=True)),
                ('denominator_mode', models.CharField(choices=[('base_scope_total', 'Percent of Base Scope'), ('absolute_only', 'Absolute Amount')], default='base_scope_total', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationGapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_key_snapshot', models.SlugField(max_length=100)),
                ('bucket_label_snapshot', models.CharField(max_length=150)),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gap_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_percent', models.DecimalField(decimal_places=6, max_digits=9)),
                ('target_percent', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gap_percent', models.DecimalField(decimal_places=6, max_digits=9)),
                ('holding_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-gap_value'],
            },
        ),
        migrations.CreateModel(
            name='AllocationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_value_identifier', models.SlugField(default='current_value', help_text='Schema identifier used as the base value for allocation math.', max_length=100)),
                ('base_scope', models.CharField(choices=[('total_portfolio', 'Total Portfolio'), ('account_type', 'Single Account Type')], default='total_portfolio', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('target_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('min_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('max_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'key'],
            },
        ),
    ]
