# Generated by Django 6.0.2 on 2026-02-19 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('allocations', '0001_initial'),
        ('portfolios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationevaluationrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationgapresult',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='allocations.allocationdimension'),
        ),
        migrations.AddField(
            model_name='allocationgapresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='allocations.allocationevaluationrun'),
        ),
        migrations.AddField(
            model_name='allocationplan',
            name='account_type',
            field=models.ForeignKey(blank=True, help_text='Required only when base_scope=account_type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_plans', to='accounts.accounttype'),
        ),
        migrations.AddField(
            model_name='allocationplan',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_plans', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='allocationscenario',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='allocations.allocationplan'),
        ),
        migrations.AddField(
            model_name='allocationevaluationrun',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='allocations.allocationscenario'),
        ),
        migrations.AddField(
            model_name='allocationdimension',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='allocations.allocationscenario'),
        ),
        migrations.AddField(
            model_name='allocationtarget',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='allocations.allocationdimension'),
        ),
        migrations.AddField(
            model_name='allocationgapresult',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='allocations.allocationtarget'),
        ),
        migrations.AddIndex(
            model_name='allocationplan',
            index=models.Index(fields=['portfolio', 'is_active'], name='allocations_portfol_818ffc_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationplan',
            constraint=models.UniqueConstraint(fields=('portfolio', 'name'), name='uniq_allocation_plan_name_per_portfolio'),
        ),
        migrations.AddIndex(
            model_name='allocationscenario',
            index=models.Index(fields=['plan', 'is_active'], name='allocations_plan_id_bfea3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationscenario',
            constraint=models.UniqueConstraint(fields=('plan', 'name'), name='uniq_allocation_scenario_name_per_plan'),
        ),
        migrations.AddIndex(
            model_name='allocationevaluationrun',
            index=models.Index(fields=['scenario', '-created_at'], name='allocations_scenari_b1ac9a_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationevaluationrun',
            index=models.Index(fields=['status'], name='allocations_status_6fb6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationdimension',
            index=models.Index(fields=['scenario', 'is_active', 'display_order'], name='allocations_scenari_309cd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationdimension',
            constraint=models.UniqueConstraint(fields=('scenario', 'name'), name='uniq_allocation_dimension_name_per_scenario'),
        ),
        migrations.AddConstraint(
            model_name='allocationtarget',
            constraint=models.UniqueConstraint(fields=('dimension', 'key'), name='uniq_allocation_target_key_per_dimension'),
        ),
        migrations.AddIndex(
            model_name='allocationgapresult',
            index=models.Index(fields=['run', 'dimension'], name='allocations_run_id_92f4c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationgapresult',
            constraint=models.UniqueConstraint(fields=('run', 'dimension', 'bucket_key_snapshot'), name='uniq_allocation_gap_bucket_per_run_dimension'),
        ),
    ]
