# Generated by Django 5.2.3 on 2025-06-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_accounts', to='portfolios.stockportfolio'),
        ),
        migrations.AddField(
            model_name='selfmanagedaccount',
            name='active_schema',
            field=models.ForeignKey(blank=True, help_text='Schema used to display stock holdings for this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schemas.stockportfolioschema'),
        ),
        migrations.AddField(
            model_name='selfmanagedaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_managed_accounts', to='portfolios.stockportfolio'),
        ),
        migrations.AddConstraint(
            model_name='managedaccount',
            constraint=models.UniqueConstraint(fields=('stock_portfolio', 'name'), name='unique_managedaccount_name_in_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='selfmanagedaccount',
            constraint=models.UniqueConstraint(fields=('stock_portfolio', 'name'), name='unique_selfmanagedstockaccount_name_in_portfolio'),
        ),
    ]
