# Generated by Django 5.2.4 on 2025-07-14 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_storagefacility'),
        ('portfolios', '0002_metalportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagefacility',
            name='metals_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_facilities', to='portfolios.metalportfolio'),
        ),
    ]
