SYSTEM_DATATYPES = [
    {
        "slug": "decimal",
        "name": "Decimal",
        "description": "Numerical values with decimal places.",
        "supports_length": False,
        "supports_decimals": True,
        "supports_numeric_limits": True,
        "supports_regex": False,
    },
    {
        "slug": "string",
        "name": "String",
        "description": "Arbitrary text values.",
        "supports_length": True,
        "supports_decimals": False,
        "supports_numeric_limits": False,
        "supports_regex": True,
    },
    {
        "slug": "date",
        "name": "Date",
        "description": "Calendar date.",
        "supports_length": False,
        "supports_decimals": False,
        "supports_numeric_limits": False,
        "supports_regex": False,
    },
    {
        "slug": "url",
        "name": "URL",
        "description": "Website link or external reference.",
        "supports_length": True,
        "supports_decimals": False,
        "supports_numeric_limits": False,
        "supports_regex": True,
    },
]
