# Generated by Django 6.0.2 on 2026-02-19 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('fx', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='portfoliodenomination',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_denominations', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='portfoliodenomination',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_denominations', to='fx.fxcurrency'),
        ),
        migrations.AddField(
            model_name='portfoliodenomination',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliovaluationsnapshot',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_snapshots', to='portfolios.portfolio'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['profile', 'kind'], name='portfolios__profile_61b397_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'personal')), fields=('profile',), name='unique_personal_portfolio_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='unique_portfolio_name_prt_profile'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client_name__isnull', True), ('kind', 'personal')), models.Q(('client_name', ''), ('kind', 'personal')), models.Q(('client_name__isnull', False), ('kind', 'client'), models.Q(('client_name', ''), _negated=True)), _connector='OR'), name='client_name_required_for_client_portfolio'),
        ),
        migrations.AddIndex(
            model_name='portfoliodenomination',
            index=models.Index(fields=['portfolio', 'is_active', 'display_order'], name='portfolios__portfol_3ae657_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfoliodenomination',
            constraint=models.UniqueConstraint(fields=('portfolio', 'key'), name='uniq_portfolio_denomination_key'),
        ),
        migrations.AddIndex(
            model_name='portfoliovaluationsnapshot',
            index=models.Index(fields=['portfolio', '-captured_at'], name='portfolios__portfol_d4a540_idx'),
        ),
    ]
