# Generated by Django 6.0.2 on 2026-02-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_navigationstate_preferences'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardlayoutstate',
            new_name='portfolios__profile_0605c2_idx',
            old_name='portfolios_d_profile_36089e_idx',
        ),
        migrations.RenameIndex(
            model_name='navigationstate',
            new_name='portfolios__profile_152969_idx',
            old_name='portfolios_n_profile_5f90e4_idx',
        ),
    ]
