# Generated by Django 6.0.2 on 2026-02-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the plan (e.g., Free, Premium, Premium+).', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Unique slug used for referencing the plan in URLs.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the plan features.')),
                ('max_stocks', models.PositiveIntegerField(default=10, help_text='Maximum number of stocks a user can track under this plan.')),
                ('allow_crypto', models.BooleanField(default=False, help_text='Indicates if this plan allows tracking of crypto assets.')),
                ('allow_metals', models.BooleanField(default=False, help_text='Indicates if this plan allows tracking of metal assets.')),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price for the plan. Zero for Free tier.', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Determines if the plan is available for subscription.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price_per_month'],
            },
        ),
    ]
