# Generated by Codex on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="advanced_analytics_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="allocations_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="client_mode_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="custom_asset_types_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="custom_assets_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="custom_schemas_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Public plans are visible to users in the plan listing endpoint.",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_accounts_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_crypto_holdings",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_equity_accounts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_holdings_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_portfolios",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_real_estate_holdings",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_stock_holdings",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="team_members_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("pro", "Pro"),
                    ("wealth_manager", "Wealth Manager"),
                ],
                default="free",
                help_text="Canonical tier classification used for entitlement logic.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trialing", "Trialing"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]

