"""
subscriptions.tests.test_models
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tests for the Plan model's behavior and constraints.
"""

from django.test import TestCase
from subscriptions.models import Plan


class PlanModelTests(TestCase):
    """
    Tests for Plan model creation and slug behavior.
    """

    def test_plan_slug_autogenerated_if_missing(self):
        """
        Slug should be automatically generated from the name if not provided.
        """
        plan = Plan.objects.create(
            name="Gold",
            description="Gold tier plan",
            max_stocks=500,
            allow_crypto=True,
            allow_metals=True,
            price_per_month=29.99
        )
        self.assertEqual(plan.slug, "gold")

    def test_plan_str_representation(self):
        """
        __str__ method should return name and price.
        """
        plan = Plan.objects.create(
            name="Free",
            slug="free",
            description="Free plan",
            price_per_month=0
        )
        self.assertIn("Free", str(plan))
