# Generated by Django 6.0.2 on 2026-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Portfolio', max_length=100)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('client', 'Client')], default='personal', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('profile_currency', 'Profile Currency'), ('currency', 'Currency'), ('asset_units', 'Asset Units')], max_length=30)),
                ('reference_code', models.CharField(blank=True, help_text='External identifier used to resolve an asset (e.g. BTC, AAPL, GCUSD).', max_length=30, null=True)),
                ('unit_label', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value_identifier', models.SlugField(default='current_value', max_length=100)),
                ('profile_currency_code', models.CharField(max_length=3)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('denominations', models.JSONField(blank=True, default=list)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
