# Generated by Django 6.0.2 on 2026-02-19 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('analytics', '0002_initial'),
        ('assets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytic_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.analyticrun'),
        ),
        migrations.AddField(
            model_name='assetdimensionexposure',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytic_exposures', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetdimensionexposure',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_exposures', to='analytics.analyticdimension'),
        ),
        migrations.AddField(
            model_name='dimensionbucket',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='analytics.analyticdimension'),
        ),
        migrations.AddField(
            model_name='dimensionbucket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='analytics.dimensionbucket'),
        ),
        migrations.AddField(
            model_name='assetdimensionexposure',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_exposures', to='analytics.dimensionbucket'),
        ),
        migrations.AddField(
            model_name='analyticresult',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='analytics.dimensionbucket'),
        ),
        migrations.AddField(
            model_name='holdingdimensionexposureoverride',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_exposure_overrides', to='analytics.dimensionbucket'),
        ),
        migrations.AddField(
            model_name='holdingdimensionexposureoverride',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_exposure_overrides', to='analytics.analyticdimension'),
        ),
        migrations.AddField(
            model_name='holdingdimensionexposureoverride',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytic_exposure_overrides', to='accounts.holding'),
        ),
        migrations.AddIndex(
            model_name='analytic',
            index=models.Index(fields=['portfolio', 'is_active'], name='analytics_a_portfol_d20438_idx'),
        ),
        migrations.AddConstraint(
            model_name='analytic',
            constraint=models.UniqueConstraint(fields=('portfolio', 'name'), name='uniq_analytic_name_per_portfolio'),
        ),
        migrations.AddIndex(
            model_name='analyticdimension',
            index=models.Index(fields=['analytic', 'is_active', 'display_order'], name='analytics_a_analyti_d691a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticdimension',
            constraint=models.UniqueConstraint(fields=('analytic', 'name'), name='uniq_dimension_name_per_analytic'),
        ),
        migrations.AddIndex(
            model_name='analyticrun',
            index=models.Index(fields=['analytic', '-created_at'], name='analytics_a_analyti_b8a078_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticrun',
            index=models.Index(fields=['status'], name='analytics_a_status_bc5e79_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionbucket',
            index=models.Index(fields=['dimension', 'is_active', 'display_order'], name='analytics_d_dimensi_b105e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='dimensionbucket',
            constraint=models.UniqueConstraint(fields=('dimension', 'key'), name='uniq_bucket_key_per_dimension'),
        ),
        migrations.AddIndex(
            model_name='assetdimensionexposure',
            index=models.Index(fields=['dimension', 'asset'], name='analytics_a_dimensi_3562f0_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdimensionexposure',
            index=models.Index(fields=['dimension', 'bucket'], name='analytics_a_dimensi_8d43f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetdimensionexposure',
            constraint=models.UniqueConstraint(fields=('dimension', 'asset', 'bucket'), name='uniq_asset_bucket_exposure'),
        ),
        migrations.AddConstraint(
            model_name='assetdimensionexposure',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 1)), name='asset_exposure_weight_between_0_and_1'),
        ),
        migrations.AddIndex(
            model_name='analyticresult',
            index=models.Index(fields=['run', 'dimension'], name='analytics_a_run_id_f78225_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticresult',
            constraint=models.UniqueConstraint(fields=('run', 'dimension', 'bucket_label_snapshot'), name='uniq_result_bucket_per_run_dimension'),
        ),
        migrations.AddIndex(
            model_name='holdingdimensionexposureoverride',
            index=models.Index(fields=['dimension', 'holding'], name='analytics_h_dimensi_432a64_idx'),
        ),
        migrations.AddIndex(
            model_name='holdingdimensionexposureoverride',
            index=models.Index(fields=['dimension', 'bucket'], name='analytics_h_dimensi_2fab17_idx'),
        ),
        migrations.AddConstraint(
            model_name='holdingdimensionexposureoverride',
            constraint=models.UniqueConstraint(fields=('dimension', 'holding', 'bucket'), name='uniq_holding_bucket_exposure_override'),
        ),
        migrations.AddConstraint(
            model_name='holdingdimensionexposureoverride',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 1)), name='holding_exposure_weight_between_0_and_1'),
        ),
    ]
