# Generated by Django 6.0.2 on 2026-02-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the plan (e.g., Free, Pro, Wealth Manager).', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Unique slug used for referencing the plan in URLs.', unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('wealth_manager', 'Wealth Manager')], default='free', help_text='Canonical tier classification used for entitlement logic.', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the plan features.')),
                ('max_stocks', models.PositiveIntegerField(default=10, help_text='Maximum number of stocks a user can track under this plan.')),
                ('allow_crypto', models.BooleanField(default=False, help_text='Indicates if this plan allows tracking of crypto assets.')),
                ('allow_metals', models.BooleanField(default=False, help_text='Indicates if this plan allows tracking of metal assets.')),
                ('max_portfolios', models.PositiveIntegerField(default=1)),
                ('max_accounts_total', models.PositiveIntegerField(blank=True, null=True)),
                ('max_equity_accounts', models.PositiveIntegerField(blank=True, null=True)),
                ('max_holdings_total', models.PositiveIntegerField(blank=True, null=True)),
                ('max_stock_holdings', models.PositiveIntegerField(blank=True, null=True)),
                ('max_crypto_holdings', models.PositiveIntegerField(blank=True, null=True)),
                ('max_real_estate_holdings', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_assets_enabled', models.BooleanField(default=False)),
                ('custom_asset_types_enabled', models.BooleanField(default=False)),
                ('custom_schemas_enabled', models.BooleanField(default=False)),
                ('advanced_analytics_enabled', models.BooleanField(default=False)),
                ('allocations_enabled', models.BooleanField(default=False)),
                ('client_mode_enabled', models.BooleanField(default=False)),
                ('team_members_enabled', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True, help_text='Public plans are visible to users in the plan listing endpoint.')),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price for the plan. Zero for Free tier.', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Determines if the plan is available for subscription.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price_per_month'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
