# Generated by Django 5.2.4 on 2025-07-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('CA', 'Canada'), ('CN', 'China'), ('FR', 'France'), ('DE', 'Germany'), ('IN', 'India'), ('JP', 'Japan'), ('CH', 'Switzerland'), ('GB', 'United Kingdom'), ('US', 'United States')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', max_length=5),
        ),
    ]
