# Generated by Django 5.2.8 on 2025-11-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_country'),
        ('users', '0002_alter_profile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, help_text='User-selected country (from ISO-3166)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='fx.country'),
        ),
    ]
