# Generated by Django 5.2.5 on 2025-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_currency',
        ),
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', max_length=3),
        ),
    ]
