# Generated by Django 6.0.2 on 2026-03-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_schema_override'),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='allowed_asset_types',
            field=models.ManyToManyField(blank=True, help_text='Optional account-level supported asset types. Leave empty to allow all asset types.', related_name='accounts_with_restrictions', to='assets.assettype'),
        ),
        migrations.AlterField(
            model_name='account',
            name='enforce_restrictions',
            field=models.BooleanField(default=False, help_text='Whether supported asset types should be treated as a hard rule instead of guidance.'),
        ),
    ]
