# Generated by Django 6.0.2 on 2026-03-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='broker',
        ),
    ]
