# Generated by Django 5.2.6 on 2025-09-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('equity', 'Equities'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('bond', 'Bonds'), ('real_estate', 'Real Estate'), ('custom', 'Custom')], db_index=True, max_length=20)),
                ('symbol', models.CharField(blank=True, db_index=True, help_text='Ticker or unique code (required for traded assets, optional for real estate/custom).', max_length=20, null=True)),
                ('name', models.CharField(help_text='Human-readable name (company, property, or custom asset).', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('symbol', None), _negated=True), fields=('asset_type', 'symbol'), name='uniq_asset_type_symbol')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=12, default=0, help_text='Number of units owned (shares, coins, ounces, etc.)', max_digits=30)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=12, help_text='Purchase price per unit in account currency', max_digits=30, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.asset')),
            ],
            options={
                'ordering': ['account', 'asset'],
                'unique_together': {('account', 'asset')},
            },
        ),
    ]
