# Generated by Django 5.2.6 on 2025-09-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, help_text='Stock exchange short code (e.g., NYSE, NASDAQ)', max_length=50, null=True)),
                ('exchange_full_name', models.CharField(blank=True, help_text='Full name of the exchange', max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('country', models.CharField(blank=True, help_text='Country of primary listing', max_length=100, null=True)),
                ('isin', models.CharField(blank=True, help_text='ISIN identifier (international securities)', max_length=12, null=True)),
                ('cusip', models.CharField(blank=True, help_text='CUSIP identifier (US securities)', max_length=12, null=True)),
                ('cik', models.CharField(blank=True, max_length=10, null=True)),
                ('ipo_date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('is_etf', models.BooleanField(default=False)),
                ('is_adr', models.BooleanField(default=False)),
                ('is_mutual_fund', models.BooleanField(default=False, help_text='True if this asset is a mutual fund')),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, help_text='Last synced market price', max_digits=20, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('previous_close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('average_volume', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ps_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('peg_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('dividend_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('ex_dividend_date', models.DateField(blank=True, null=True)),
                ('dividend_payout_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=4, help_text='Net Asset Value per share', max_digits=20, null=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Annual fee ratio', max_digits=6, null=True)),
                ('fund_family', models.CharField(blank=True, max_length=100, null=True)),
                ('fund_category', models.CharField(blank=True, max_length=100, null=True)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('turnover_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('underlying_index', models.CharField(blank=True, max_length=100, null=True)),
                ('aum', models.BigIntegerField(blank=True, help_text='Assets under management', null=True)),
                ('holdings_count', models.IntegerField(blank=True, null=True)),
                ('tracking_error', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('premium_discount', models.DecimalField(blank=True, decimal_places=4, help_text='Premium (+) or discount (-) to NAV, as a ratio', max_digits=6, null=True)),
                ('preferred_par_value', models.DecimalField(blank=True, decimal_places=2, help_text='Par value of preferred shares', max_digits=10, null=True)),
                ('preferred_coupon_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Coupon rate (%) for preferred shares', max_digits=6, null=True)),
                ('call_date', models.DateField(blank=True, help_text='Earliest call date for callable preferred shares', null=True)),
                ('esg_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbon_intensity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True if user-defined (not synced from provider)')),
                ('listing_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELISTED', 'Delisted'), ('SUSPENDED', 'Suspended'), ('IPO', 'IPO Pending')], db_index=True, default='ACTIVE', help_text='Tracks whether the equity is currently listed and tradable.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(limit_choices_to={'asset_type': 'equity'}, on_delete=django.db.models.deletion.CASCADE, related_name='equity_detail', to='assets.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['exchange'], name='assets_equi_exchang_77d1b8_idx'), models.Index(fields=['is_custom'], name='assets_equi_is_cust_aedda2_idx'), models.Index(fields=['is_etf'], name='assets_equi_is_etf_e22122_idx'), models.Index(fields=['is_mutual_fund'], name='assets_equi_is_mutu_832740_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('isin', None), _negated=True), fields=('isin',), name='uniq_equity_isin'), models.UniqueConstraint(condition=models.Q(('cusip', None), _negated=True), fields=('cusip',), name='uniq_equity_cusip'), models.UniqueConstraint(condition=models.Q(('cik', None), _negated=True), fields=('cik',), name='uniq_equity_cik')],
            },
        ),
    ]
