# Generated by Django 5.2.4 on 2025-07-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetSchemaConfig',
        ),
    ]
