# Generated by Django 5.2.6 on 2025-09-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('assets', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttheme',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tags', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='holdingthemevalue',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.investmenttheme'),
        ),
        migrations.AddIndex(
            model_name='preciousmetal',
            index=models.Index(fields=['symbol'], name='assets_prec_symbol_85bb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='preciousmetal',
            index=models.Index(fields=['is_custom'], name='assets_prec_is_cust_07b154_idx'),
        ),
        migrations.AddField(
            model_name='preciousmetalholding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metal_holdings', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='preciousmetalholding',
            name='precious_metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.preciousmetal'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['ticker'], name='assets_stoc_ticker_e1a3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_custom'], name='assets_stoc_is_cust_490ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange'], name='assets_stoc_exchang_da706b_idx'),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='assets.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='investmenttheme',
            unique_together={('portfolio', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='holdingthemevalue',
            unique_together={('holding_ct', 'holding_id', 'theme')},
        ),
        migrations.AddIndex(
            model_name='preciousmetalholding',
            index=models.Index(fields=['account'], name='assets_prec_account_2cb6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='preciousmetalholding',
            index=models.Index(fields=['precious_metal'], name='assets_prec_preciou_e401e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='preciousmetalholding',
            constraint=models.UniqueConstraint(fields=('account', 'precious_metal'), name='unique_precious_metal_per_account'),
        ),
        migrations.AddIndex(
            model_name='stockholding',
            index=models.Index(fields=['account'], name='assets_stoc_account_388ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockholding',
            index=models.Index(fields=['stock'], name='assets_stoc_stock_i_44c9e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockholding',
            constraint=models.UniqueConstraint(fields=('account', 'stock'), name='unique_stock_holding_per_account'),
        ),
    ]
