# Generated by Django 5.2.5 on 2025-08-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('assets', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttheme',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tags', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='holdingthemevalue',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.investmenttheme'),
        ),
        migrations.AddIndex(
            model_name='preciousmetal',
            index=models.Index(fields=['symbol'], name='assets_prec_symbol_85bb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='preciousmetal',
            index=models.Index(fields=['is_custom'], name='assets_prec_is_cust_07b154_idx'),
        ),
        migrations.AddField(
            model_name='preciousmetalholding',
            name='investment_theme',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_investments', to='assets.investmenttheme'),
        ),
        migrations.AddField(
            model_name='preciousmetalholding',
            name='precious_metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precious_metal_holdings', to='assets.preciousmetal'),
        ),
        migrations.AddField(
            model_name='preciousmetalholding',
            name='storage_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.storagefacility'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['ticker'], name='assets_stoc_ticker_e1a3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_custom'], name='assets_stoc_is_cust_490ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange'], name='assets_stoc_exchang_da706b_idx'),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='investment_theme',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_investments', to='assets.investmenttheme'),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='self_managed_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.selfmanagedaccount'),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to='assets.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='investmenttheme',
            unique_together={('portfolio', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='holdingthemevalue',
            unique_together={('holding_ct', 'holding_id', 'theme')},
        ),
        migrations.AddIndex(
            model_name='preciousmetalholding',
            index=models.Index(fields=['storage_facility'], name='assets_prec_storage_9dedd8_idx'),
        ),
        migrations.AddIndex(
            model_name='preciousmetalholding',
            index=models.Index(fields=['precious_metal'], name='assets_prec_preciou_e401e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='preciousmetalholding',
            constraint=models.UniqueConstraint(fields=('storage_facility', 'precious_metal'), name='unique_precious_metal_per_storage'),
        ),
        migrations.AddIndex(
            model_name='stockholding',
            index=models.Index(fields=['self_managed_account'], name='assets_stoc_self_ma_aad51b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockholding',
            index=models.Index(fields=['stock'], name='assets_stoc_stock_i_44c9e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockholding',
            constraint=models.UniqueConstraint(fields=('self_managed_account', 'stock'), name='unique_holding_per_account'),
        ),
    ]
