# Generated by Django 5.2.6 on 2025-09-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('cusip', models.CharField(blank=True, max_length=12, null=True)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('bond_type', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_rate', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('coupon_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('yield_to_maturity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('yield_to_call', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('current_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('accrued_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('convexity', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('par_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('issue_size', models.BigIntegerField(blank=True, null=True)),
                ('outstanding_amount', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, help_text='Stock exchange short code (e.g., NYSE, NASDAQ)', max_length=50, null=True)),
                ('exchange_full_name', models.CharField(blank=True, help_text='Full name of the exchange', max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('country', models.CharField(blank=True, help_text='Country of primary listing', max_length=100, null=True)),
                ('cusip', models.CharField(blank=True, help_text='CUSIP identifier (US securities)', max_length=12, null=True)),
                ('isin', models.CharField(blank=True, help_text='ISIN identifier (international securities)', max_length=12, null=True)),
                ('ipo_date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('is_etf', models.BooleanField(default=False)),
                ('is_adr', models.BooleanField(default=False)),
                ('is_mutual_fund', models.BooleanField(default=False, help_text='True if this asset is a mutual fund')),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, help_text='Last synced market price', max_digits=20, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('previous_close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('average_volume', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ps_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('peg_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('dividend_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('ex_dividend_date', models.DateField(blank=True, null=True)),
                ('dividend_payout_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=4, help_text='Net Asset Value per share', max_digits=20, null=True)),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Annual fee ratio', max_digits=6, null=True)),
                ('fund_family', models.CharField(blank=True, max_length=100, null=True)),
                ('fund_category', models.CharField(blank=True, max_length=100, null=True)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('turnover_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('underlying_index', models.CharField(blank=True, max_length=100, null=True)),
                ('aum', models.BigIntegerField(blank=True, help_text='Assets under management', null=True)),
                ('holdings_count', models.IntegerField(blank=True, null=True)),
                ('tracking_error', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('premium_discount', models.DecimalField(blank=True, decimal_places=4, help_text='Premium (+) or discount (-) to NAV, as a ratio', max_digits=6, null=True)),
                ('preferred_par_value', models.DecimalField(blank=True, decimal_places=2, help_text='Par value of preferred shares', max_digits=10, null=True)),
                ('preferred_coupon_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Coupon rate (%) for preferred shares', max_digits=6, null=True)),
                ('call_date', models.DateField(blank=True, help_text='Earliest call date for callable preferred shares', null=True)),
                ('esg_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbon_intensity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True if user-defined (not synced from provider)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='changes_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='24h change percentage', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='day_high',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='day_low',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='total_supply',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='volume_24h',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='year_high',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='year_low',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='metaldetail',
            name='day_high',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Intraday high', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='metaldetail',
            name='day_low',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Intraday low', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='metaldetail',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Opening price for the trading session', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='metaldetail',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Previous session close', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='metaldetail',
            name='volume',
            field=models.BigIntegerField(blank=True, help_text='Trading volume if available (sometimes blank for metals)', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('equity', 'Equities'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('bond', 'Bonds'), ('real_estate', 'Real Estate'), ('custom', 'Custom')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='Human-readable name (company, property, or custom asset).', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(blank=True, db_index=True, help_text='Ticker or unique code (required for traded assets, optional for real estate/custom).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cryptodetail',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Last synced market price', max_digits=30, null=True),
        ),
        migrations.AddIndex(
            model_name='cryptodetail',
            index=models.Index(fields=['exchange'], name='assets_cryp_exchang_5d13a0_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptodetail',
            index=models.Index(fields=['currency'], name='assets_cryp_currenc_2c1fde_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptodetail',
            index=models.Index(fields=['is_custom'], name='assets_cryp_is_cust_fd930e_idx'),
        ),
        migrations.AddIndex(
            model_name='metaldetail',
            index=models.Index(fields=['currency'], name='assets_meta_currenc_54055a_idx'),
        ),
        migrations.AddIndex(
            model_name='metaldetail',
            index=models.Index(fields=['is_custom'], name='assets_meta_is_cust_43d0e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('symbol', None), _negated=True), fields=('asset_type', 'symbol'), name='uniq_asset_type_symbol'),
        ),
        migrations.AddField(
            model_name='bonddetail',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type': 'bond'}, on_delete=django.db.models.deletion.CASCADE, related_name='bond_detail', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='equitydetail',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type': 'equity'}, on_delete=django.db.models.deletion.CASCADE, related_name='equity_detail', to='assets.asset'),
        ),
        migrations.DeleteModel(
            name='StockDetail',
        ),
        migrations.AddIndex(
            model_name='equitydetail',
            index=models.Index(fields=['exchange'], name='assets_equi_exchang_77d1b8_idx'),
        ),
        migrations.AddIndex(
            model_name='equitydetail',
            index=models.Index(fields=['is_custom'], name='assets_equi_is_cust_aedda2_idx'),
        ),
        migrations.AddIndex(
            model_name='equitydetail',
            index=models.Index(fields=['is_etf'], name='assets_equi_is_etf_e22122_idx'),
        ),
        migrations.AddIndex(
            model_name='equitydetail',
            index=models.Index(fields=['is_mutual_fund'], name='assets_equi_is_mutu_832740_idx'),
        ),
    ]
