# Generated by Django 6.0.2 on 2026-02-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealEstateCashflow',
        ),
    ]
