# Generated by Django 5.2.8 on 2025-11-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=30, help_text='Purchase price per unit in account currency', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.DecimalField(decimal_places=30, default=0, help_text='Number of units owned (shares, coins, ounces, etc.)', max_digits=50),
        ),
    ]
