# Generated by Django 6.0.1 on 2026-01-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('fx', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Null = system-defined asset type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='users.profile'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='fx.country'),
        ),
        migrations.AddField(
            model_name='realestatetype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='NULL = system type; otherwise user-owned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_types', to='users.profile'),
        ),
        migrations.AddField(
            model_name='commodityasset',
            name='currency',
            field=models.ForeignKey(help_text='Currency this commodity is priced in (USD).', on_delete=django.db.models.deletion.PROTECT, related_name='commodity_assets', to='fx.fxcurrency'),
        ),
        migrations.AddField(
            model_name='cryptoyield',
            name='crypto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_profile', to='assets.cryptoasset'),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='currency',
            field=models.ForeignKey(help_text='Currency this crypto is priced in (usually USD).', on_delete=django.db.models.deletion.PROTECT, related_name='crypto_assets', to='fx.fxcurrency'),
        ),
        migrations.AddField(
            model_name='customasset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_assets', to='fx.fxcurrency'),
        ),
        migrations.AddField(
            model_name='customasset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_assets', to='users.profile'),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equities', to='fx.country'),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equities', to='fx.fxcurrency'),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equities', to='assets.exchange'),
        ),
        migrations.AddField(
            model_name='preciousmetalasset',
            name='commodity',
            field=models.ForeignKey(help_text='Commodity spot price used for valuation (e.g. GCUSD).', on_delete=django.db.models.deletion.PROTECT, related_name='precious_metals', to='assets.commodityasset'),
        ),
        migrations.AddField(
            model_name='realestatecashflow',
            name='real_estate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow', to='assets.realestateasset'),
        ),
        migrations.AddField(
            model_name='realestateasset',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_assets', to='fx.country'),
        ),
        migrations.AddField(
            model_name='realestateasset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_estate_assets', to='fx.fxcurrency'),
        ),
        migrations.AddField(
            model_name='realestateasset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_assets', to='users.profile'),
        ),
        migrations.AddField(
            model_name='realestateasset',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='assets.realestatetype'),
        ),
        migrations.AddIndex(
            model_name='assetprice',
            index=models.Index(fields=['last_updated'], name='assets_asse_last_up_21e7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='assetprice',
            index=models.Index(fields=['source'], name='assets_asse_source_dbe1d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_asset_type_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(fields=('created_by', 'slug'), name='unique_asset_Type_slug_per_user'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asse_asset_t_22f697_idx'),
        ),
        migrations.AddConstraint(
            model_name='realestatetype',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', True)), fields=('name',), name='uniq_system_real_estate_type'),
        ),
        migrations.AddConstraint(
            model_name='realestatetype',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False)), fields=('name', 'created_by'), name='uniq_user_real_estate_type'),
        ),
        migrations.AddIndex(
            model_name='equityasset',
            index=models.Index(fields=['ticker'], name='assets_equi_ticker_c6199d_idx'),
        ),
        migrations.AddIndex(
            model_name='equityasset',
            index=models.Index(fields=['exchange'], name='assets_equi_exchang_34ab2d_idx'),
        ),
        migrations.AddIndex(
            model_name='equityasset',
            index=models.Index(fields=['sector'], name='assets_equi_sector_40fd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='equityasset',
            index=models.Index(fields=['industry'], name='assets_equi_industr_6b2c1b_idx'),
        ),
    ]
