# Generated by Django 5.2.8 on 2025-11-13 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdatacache',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cryptodetail',
            name='assets_cryp_exchang_5d13a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='cryptodetail',
            name='assets_cryp_currenc_2c1fde_idx',
        ),
        migrations.RemoveIndex(
            model_name='cryptodetail',
            name='assets_cryp_is_cust_fd930e_idx',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='changes_percentage',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='circulating_supply',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='day_high',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='day_low',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='decimals',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='previous_close',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='total_supply',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='volume_24h',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='year_high',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='year_low',
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='base_symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='quote_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assetidentifier',
            name='id_type',
            field=models.CharField(choices=[('TICKER', 'Ticker'), ('ISIN', 'ISIN'), ('CUSIP', 'CUSIP'), ('CIK', 'CIK'), ('BASE_SYMBOL', 'Base Symbol'), ('PAIR_SYMBOL', 'Pair Symbol')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='assetidentifier',
            name='value',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptodetail',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketdatacache',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type__in': ['equity', 'crypto', 'bond', 'metal']}, on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='marketdatacache',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='cryptodetail',
            index=models.Index(fields=['base_symbol'], name='assets_cryp_base_sy_130944_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptodetail',
            index=models.Index(fields=['quote_currency'], name='assets_cryp_quote_c_815d47_idx'),
        ),
    ]
