# Generated by Django 5.2.8 on 2025-11-27 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Default currency in which this asset is quoted or valued.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fx.fxcurrency'),
        ),
    ]
