# Generated by Django 5.2.8 on 2025-11-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_currency'),
        ('fx', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equitydetail',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country of primary listing (ISO-3166).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_listings', to='fx.country'),
        ),
    ]
