# Generated by Django 5.2.8 on 2025-11-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_marketdatacache_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetidentifier',
            unique_together={('asset', 'id_type', 'value')},
        ),
    ]
