# Generated by Django 6.0 on 2025-12-06 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bonddetail',
            name='uniq_bond_isin',
        ),
        migrations.RemoveConstraint(
            model_name='bonddetail',
            name='uniq_bond_cusip',
        ),
        migrations.AlterField(
            model_name='bonddetail',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bond_detail', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='bonddetail',
            name='coupon_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cryptodetail',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_detail', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type__slug': 'equity'}, on_delete=django.db.models.deletion.CASCADE, related_name='equity_detail', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='marketdatacache',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type__slug__in': ['equity', 'crypto', 'bond', 'metal']}, on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='metaldetail',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type__slug': 'metal'}, on_delete=django.db.models.deletion.CASCADE, related_name='metal_detail', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='metaldetail',
            name='volume',
            field=models.BigIntegerField(blank=True, help_text='Trading volume if available (may not exist for metals)', null=True),
        ),
        migrations.AlterField(
            model_name='realestatedetail',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type__slug': 'real_estate'}, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_detail', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='realestatedetail',
            name='property_type',
            field=models.ForeignKey(blank=True, help_text='Type of property (e.g. Single-Family, Duplex, Commercial).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='assets.realestatetype'),
        ),
        migrations.AddConstraint(
            model_name='bonddetail',
            constraint=models.UniqueConstraint(condition=models.Q(('isin__isnull', False)), fields=('isin',), name='uniq_bond_isin'),
        ),
        migrations.AddConstraint(
            model_name='bonddetail',
            constraint=models.UniqueConstraint(condition=models.Q(('cusip__isnull', False)), fields=('cusip',), name='uniq_bond_cusip'),
        ),
    ]
