# Generated by Django 6.0.1 on 2026-01-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreciousMetalAsset',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='precious_metal', serialize=False, to='assets.asset')),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('palladium', 'Palladium')], db_index=True, max_length=20)),
                ('unit', models.CharField(choices=[('ozt', 'Troy Ounce'), ('g', 'Gram'), ('kg', 'Kilogram')], default='ozt', help_text='Unit that the commodity price refers to.', max_length=10)),
                ('commodity', models.ForeignKey(help_text='Commodity spot price used for valuation (e.g. GCUSD).', on_delete=django.db.models.deletion.PROTECT, related_name='precious_metals', to='assets.commodityasset')),
            ],
        ),
    ]
