# Generated by Django 6.0.1 on 2026-02-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitydividendsnapshot',
            name='forward_dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equitydividendsnapshot',
            name='trailing_dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
