# Generated by Django 6.0.1 on 2026-01-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitydividendsnapshot',
            name='cadence_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('STALE', 'Stale'), ('BROKEN', 'Broken'), ('NONE', 'None')], default='NONE', help_text='Health of the inferred regular dividend cadence.', max_length=20),
        ),
        migrations.AlterField(
            model_name='equitydividendsnapshot',
            name='regular_dividend_frequency',
            field=models.CharField(blank=True, help_text='Inferred regular dividend frequency (e.g. Quarterly).', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equitydividendsnapshot',
            name='status',
            field=models.CharField(choices=[('CONFIDENT', 'Confident'), ('UNCERTAIN', 'Uncertain'), ('INACTIVE', 'Inactive')], default='INACTIVE', help_text='Confidence in dividend forward estimates.', max_length=20),
        ),
        migrations.AlterField(
            model_name='equitydividendsnapshot',
            name='trailing_12m_cashflow',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Total dividends paid in the last 12 months (incl. specials).', max_digits=20),
        ),
        migrations.AlterField(
            model_name='equitydividendsnapshot',
            name='trailing_12m_dividend',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Sum of regular (non-special) dividends in the last 12 months.', max_digits=20),
        ),
    ]
