# Generated by Django 5.2.6 on 2025-09-22 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_equitydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('TICKER', 'Ticker'), ('ISIN', 'ISIN'), ('CUSIP', 'CUSIP'), ('CIK', 'CIK'), ('FIGI', 'FIGI'), ('INTERNAL', 'Internal Code'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('value', models.CharField(db_index=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Marks the main identifier to display/use in trading.')),
            ],
        ),
        migrations.CreateModel(
            name='BondDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('cusip', models.CharField(blank=True, max_length=12, null=True)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('bond_type', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_rate', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('coupon_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('yield_to_maturity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('yield_to_call', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('current_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('accrued_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('convexity', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('par_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('issue_size', models.BigIntegerField(blank=True, null=True)),
                ('outstanding_amount', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, help_text='Quote currency (usually USD)', max_length=10, null=True)),
                ('decimals', models.PositiveSmallIntegerField(default=8, help_text='Number of decimal places supported (BTC=8, ETH=18, etc.)')),
                ('last_price', models.DecimalField(blank=True, decimal_places=12, help_text='Last synced market price', max_digits=30, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('volume_24h', models.BigIntegerField(blank=True, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('total_supply', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('day_high', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('day_low', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('year_high', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('year_low', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('changes_percentage', models.DecimalField(blank=True, decimal_places=4, help_text='24h change percentage', max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True if user-defined (not synced from provider)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='oz', help_text='Measurement unit (e.g., ounce, gram)', max_length=20)),
                ('currency', models.CharField(blank=True, help_text='Quote currency (usually USD)', max_length=10, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, help_text='Last synced market price per unit', max_digits=20, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, help_text='Opening price for the trading session', max_digits=20, null=True)),
                ('day_high', models.DecimalField(blank=True, decimal_places=4, help_text='Intraday high', max_digits=20, null=True)),
                ('day_low', models.DecimalField(blank=True, decimal_places=4, help_text='Intraday low', max_digits=20, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=4, help_text='Previous session close', max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, help_text='Trading volume if available (sometimes blank for metals)', null=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True if user-defined (not synced from provider)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='asset',
            name='uniq_asset_type_symbol',
        ),
        migrations.RemoveConstraint(
            model_name='equitydetail',
            name='uniq_equity_isin',
        ),
        migrations.RemoveConstraint(
            model_name='equitydetail',
            name='uniq_equity_cusip',
        ),
        migrations.RemoveConstraint(
            model_name='equitydetail',
            name='uniq_equity_cik',
        ),
        migrations.RemoveIndex(
            model_name='equitydetail',
            name='assets_equi_is_cust_aedda2_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='cik',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='cusip',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='isin',
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, help_text='Default currency in which this asset is quoted or valued (if applicable).', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('equity', 'Equities'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('bond', 'Bonds'), ('real_estate', 'Real Estate'), ('custom', 'Custom')], db_index=True, help_text='General classification (Equity, Bond, Crypto, Metal, RealEstate, Custom, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, help_text='Human-readable name (filled by enrichment for tradables, user-supplied for custom/real estate).', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='call_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='currency',
            field=models.CharField(blank=True, help_text='Trading currency (usually matches Asset.currency)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='exchange',
            field=models.CharField(blank=True, help_text='Stock exchange code (e.g., NYSE, NASDAQ)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='expense_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='is_mutual_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='listing_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELISTED', 'Delisted'), ('SUSPENDED', 'Suspended'), ('IPO', 'IPO Pending')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='nav',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='preferred_coupon_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='preferred_par_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='premium_discount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asse_asset_t_529092_idx'),
        ),
        migrations.AddField(
            model_name='assetidentifier',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='bonddetail',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type': 'bond'}, on_delete=django.db.models.deletion.CASCADE, related_name='bond_detail', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type': 'crypto'}, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_detail', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='metaldetail',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type': 'metal'}, on_delete=django.db.models.deletion.CASCADE, related_name='metal_detail', to='assets.asset'),
        ),
        migrations.AddIndex(
            model_name='assetidentifier',
            index=models.Index(fields=['id_type', 'value'], name='assets_asse_id_type_ef670d_idx'),
        ),
        migrations.AddIndex(
            model_name='assetidentifier',
            index=models.Index(fields=['asset', 'is_primary'], name='assets_asse_asset_i_a4c149_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetidentifier',
            unique_together={('id_type', 'value')},
        ),
        migrations.AddConstraint(
            model_name='bonddetail',
            constraint=models.UniqueConstraint(condition=models.Q(('isin', None), _negated=True), fields=('isin',), name='uniq_bond_isin'),
        ),
        migrations.AddConstraint(
            model_name='bonddetail',
            constraint=models.UniqueConstraint(condition=models.Q(('cusip', None), _negated=True), fields=('cusip',), name='uniq_bond_cusip'),
        ),
        migrations.AddIndex(
            model_name='cryptodetail',
            index=models.Index(fields=['exchange'], name='assets_cryp_exchang_5d13a0_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptodetail',
            index=models.Index(fields=['currency'], name='assets_cryp_currenc_2c1fde_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptodetail',
            index=models.Index(fields=['is_custom'], name='assets_cryp_is_cust_fd930e_idx'),
        ),
        migrations.AddIndex(
            model_name='metaldetail',
            index=models.Index(fields=['currency'], name='assets_meta_currenc_54055a_idx'),
        ),
        migrations.AddIndex(
            model_name='metaldetail',
            index=models.Index(fields=['is_custom'], name='assets_meta_is_cust_43d0e6_idx'),
        ),
    ]
