# Generated by Django 5.2.9 on 2025-12-03 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdatacache',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type__domain__in': ['equity', 'crypto', 'bond', 'metal']}, on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='assets.asset'),
        ),
    ]
