# Generated by Django 5.2.8 on 2025-11-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_holding_purchase_price_alter_holding_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodetail',
            name='precision',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
