# Generated by Django 5.2.6 on 2025-09-11 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_bonddetail_equitydetail_remove_stockdetail_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Bond',
                'verbose_name_plural': 'Bonds',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Crypto',
                'verbose_name_plural': 'Cryptos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='CustomAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Custom Asset',
                'verbose_name_plural': 'Custom Assets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='EquityAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Equity',
                'verbose_name_plural': 'Equities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='MetalAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Metal',
                'verbose_name_plural': 'Metals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='RealEstateAsset',
            fields=[
            ],
            options={
                'verbose_name': 'Real Estate',
                'verbose_name_plural': 'Real Estate',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='CustomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(limit_choices_to={'asset_type': 'custom'}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_detail', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='City/region or address', max_length=255)),
                ('property_type', models.CharField(help_text='e.g., Residential, Commercial, Land, Mixed-use', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price originally paid', max_digits=20, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Latest estimated market value', max_digits=20, null=True)),
                ('appraisal_date', models.DateField(blank=True, help_text='Date of last valuation/appraisal', null=True)),
                ('rental_income', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly or annual rental income', max_digits=20, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Annual expenses (taxes, maintenance, insurance, etc.)', max_digits=20, null=True)),
                ('mortgage_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Outstanding mortgage balance if applicable', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(limit_choices_to={'asset_type': 'real_estate'}, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_detail', to='assets.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['location'], name='assets_real_locatio_d39498_idx'), models.Index(fields=['property_type'], name='assets_real_propert_bd7f88_idx')],
            },
        ),
    ]
