# Generated by Django 5.2.3 on 2025-06-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quote_type',
        ),
        migrations.AddField(
            model_name='stock',
            name='is_etf',
            field=models.BooleanField(default=False),
        ),
    ]
