# Generated by Django 6.0.1 on 2026-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityasset',
            name='ticker',
            field=models.CharField(db_index=True, help_text='Primary trading symbol (e.g. AAPL, MSFT).', max_length=20),
        ),
    ]
