# Generated by Django 6.0.2 on 2026-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customasset',
            name='requires_review',
            field=models.BooleanField(default=False, help_text='Indicates this asset was auto-created due to a market change and requires user review.'),
        ),
    ]
