# Generated by Django 5.2.6 on 2025-09-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciousmetalholding',
            name='investment_theme',
        ),
        migrations.RemoveField(
            model_name='stockholding',
            name='investment_theme',
        ),
    ]
