# Generated by Django 6.0.1 on 2026-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoasset',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=45, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='total_supply',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=45, null=True),
        ),
    ]
