# Generated by Django 6.0.1 on 2026-01-14 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_equitydividendsnapshot_cadence_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateasset',
            name='is_owner_occupied',
            field=models.BooleanField(default=False, help_text='True if the owner occupies this property.'),
        ),
        migrations.CreateModel(
            name='RealEstateCashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generates_income', models.BooleanField(default=False, help_text='True if the property generates rental income.')),
                ('gross_annual_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('vacancy_rate', models.DecimalField(decimal_places=2, default=0, help_text='Expected vacancy percentage (0–100).', max_digits=5)),
                ('annual_operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('annual_property_tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('annual_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('real_estate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow', to='assets.realestateasset')),
            ],
        ),
    ]
