# Generated by Django 5.2.8 on 2025-12-01 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_equitydetail_country'),
        ('fx', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, help_text='State/Province/Region', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City or locality', max_length=100)),
                ('address', models.CharField(blank=True, help_text='Full address (optional)', max_length=255)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('appraisal_date', models.DateField(blank=True, null=True)),
                ('rental_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_mortgaged', models.BooleanField(default=False)),
                ('mortgage_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('monthly_mortgage_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(limit_choices_to={'asset_type': 'real_estate'}, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_detail', to='assets.asset')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_properties', to='fx.country')),
                ('property_type', models.ForeignKey(blank=True, help_text='Category of real estate asset (e.g. Single-Family, Duplex, Commercial).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='assets.realestatetype')),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='assets_real_city_a30812_idx'), models.Index(fields=['region'], name='assets_real_region_180917_idx'), models.Index(fields=['country'], name='assets_real_country_55fc7d_idx')],
            },
        ),
    ]
