# Generated by Django 5.2.8 on 2025-11-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetidentifier_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetidentifier',
            unique_together={('id_type', 'value')},
        ),
    ]
