# Generated by Django 5.2.9 on 2025-12-04 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_marketdatacache_asset'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestatetype',
            options={},
        ),
        migrations.RenameField(
            model_name='realestatetype',
            old_name='is_custom',
            new_name='is_system',
        ),
        migrations.AddField(
            model_name='realestatetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_property_types', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='realestatetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='realestatetype',
            unique_together={('name', 'created_by')},
        ),
    ]
