# Generated by Django 6.0.2 on 2026-02-11 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_customasset_requires_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciousmetalasset',
            name='commodity',
            field=models.ForeignKey(help_text='Commodity spot price used for valuation (e.g. GCUSD).', on_delete=django.db.models.deletion.CASCADE, related_name='precious_metals', to='assets.commodityasset'),
        ),
    ]
