# Generated by Django 5.2.5 on 2025-08-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_preciousmetal_currency'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciousmetalholding',
            name='investment_theme',
        ),
        migrations.RemoveField(
            model_name='stockholding',
            name='investment_theme',
        ),
        migrations.AddField(
            model_name='preciousmetalholding',
            name='investment_theme',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_investments', to='assets.investmenttheme'),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='investment_theme',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_investments', to='assets.investmenttheme'),
        ),
        migrations.CreateModel(
            name='HoldingThemeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_id', models.PositiveIntegerField()),
                ('value_string', models.CharField(blank=True, max_length=255, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('holding_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.investmenttheme')),
            ],
            options={
                'unique_together': {('holding_ct', 'holding_id', 'theme')},
            },
        ),
    ]
