# Generated by Django 6.0.1 on 2026-01-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_equityasset_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityasset',
            name='asset',
        ),
        migrations.AddField(
            model_name='equityasset',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='ipo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='is_actively_trading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='is_adr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='is_etf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='is_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='last_dividend',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Last dividend paid per share.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='market_cap',
            field=models.BigIntegerField(blank=True, help_text='Market capitalization in quote currency.', null=True),
        ),
        migrations.AddField(
            model_name='equityasset',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equityasset',
            name='ticker',
            field=models.CharField(db_index=True, help_text='Primary trading symbol (e.g. AAPL).', max_length=20),
        ),
    ]
