# Generated by Django 5.2.6 on 2025-09-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetidentifier_bonddetail_cryptodetail_metaldetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True if this asset was manually created (not from external data).'),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='listing_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELISTED', 'Delisted'), ('SUSPENDED', 'Suspended'), ('IPO', 'IPO Pending'), ('CUSTOM', 'Custom/Unverified')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
