# Generated by Django 6.0.1 on 2026-01-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_cryptoasset_circulating_supply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_yield_percent', models.DecimalField(decimal_places=2, help_text='Expected annual yield percentage.', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('crypto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_profile', to='assets.cryptoasset')),
            ],
        ),
    ]
