# Generated by Django 5.2.6 on 2025-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_type'),
        ('assets', '0003_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['account', 'asset']},
        ),
        migrations.AddField(
            model_name='holding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Purchase price per unit in account currency', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.DecimalField(decimal_places=12, default=0, help_text='Number of units owned (shares, coins, ounces, etc.)', max_digits=30),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('account', 'asset')},
        ),
    ]
