# Generated by Django 5.2.8 on 2025-11-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_cryptodetail_precision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptodetail',
            old_name='precision',
            new_name='quantity_precision',
        ),
    ]
