# Generated by Django 6.0 on 2025-12-08 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_bonddetail_uniq_bond_isin_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable industry name (e.g., 'Semiconductors').", max_length=150)),
                ('slug', models.SlugField(help_text="URL-safe unique slug (e.g., 'semiconductors').", max_length=150)),
                ('is_system', models.BooleanField(default=False, help_text='True if this industry comes from FMP and is global for all users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='NULL for system industries. Set to user for custom industries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_industries', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=150)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_sectors', to='users.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('slug', 'owner'), name='unique_sector_slug_per_owner')],
            },
        ),
    ]
