# Generated by Django 5.2.6 on 2025-10-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_is_custom_alter_equitydetail_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetidentifier',
            name='id_type',
            field=models.CharField(choices=[('TICKER', 'Ticker'), ('ISIN', 'ISIN'), ('CUSIP', 'CUSIP'), ('CIK', 'CIK')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='equitydetail',
            name='listing_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DELISTED', 'Delisted'), ('SUSPENDED', 'Suspended'), ('IPO', 'IPO Pending'), ('PENDING', 'Pending Data'), ('COLLISION', 'Collision')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
