# Generated by Django 6.0.1 on 2026-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_cryptoyield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoasset',
            name='pair_symbol',
            field=models.CharField(db_index=True, help_text='Provider pricing pair (e.g. BTCUSD).', max_length=30),
        ),
    ]
