# Generated by Django 6.0 on 2025-12-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_industry_sector'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='unique_sector_slug_per_owner',
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='unique_system_industry_slug'),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('slug', 'owner'), name='unique_user_industry_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='unique_system_sector_slug'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('slug', 'owner'), name='unique_user_sector_slug_per_owner'),
        ),
    ]
