# Generated by Django 6.0.1 on 2026-01-15 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_realestateasset_is_owner_occupied_realestatecashflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateasset',
            name='estimated_value',
        ),
        migrations.RemoveField(
            model_name='realestateasset',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='realestateasset',
            name='asset',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='real_estate', serialize=False, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='realestateasset',
            name='is_owner_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
