# Generated by Django 5.2.6 on 2025-10-08 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_assetidentifier_id_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='aum',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='average_volume',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='call_date',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='carbon_intensity',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='dividend_payout_ratio',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='esg_score',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='expense_ratio',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='fund_category',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='fund_family',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='holdings_count',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='inception_date',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='nav',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='peg_ratio',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='preferred_coupon_rate',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='preferred_par_value',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='premium_discount',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='previous_close_price',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='ps_ratio',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='shares_outstanding',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='total_assets',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='tracking_error',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='turnover_ratio',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='underlying_index',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='volume',
        ),
        migrations.AddConstraint(
            model_name='equitydetail',
            constraint=models.UniqueConstraint(fields=('asset',), name='unique_equity_detail_asset'),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='asset',
            field=models.OneToOneField(limit_choices_to={'asset_type__in': ['equity', 'bond', 'crypto', 'metal']}, on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='assets.asset'),
        ),
        migrations.AddIndex(
            model_name='marketdatacache',
            index=models.Index(fields=['last_synced'], name='assets_mark_last_sy_0025e7_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdatacache',
            index=models.Index(fields=['asset'], name='assets_mark_asset_i_1d37f7_idx'),
        ),
    ]
