# Generated by Django 6.0.1 on 2026-01-15 18:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_cryptoasset_pair_symbol'),
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customasset',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customasset',
            name='estimated_value',
        ),
        migrations.AddField(
            model_name='customasset',
            name='attributes',
            field=models.JSONField(default=dict, help_text='Custom attributes defined by the asset type schema.'),
        ),
        migrations.AddField(
            model_name='customasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 15, 18, 15, 30, 591269, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customasset',
            name='currency',
            field=models.ForeignKey(help_text='Currency this asset is valued in.', on_delete=django.db.models.deletion.PROTECT, related_name='custom_assets', to='fx.fxcurrency'),
        ),
        migrations.CreateModel(
            name='CustomAssetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal field name (e.g. 'grade', 'card_type').", max_length=100)),
                ('label', models.CharField(help_text="Display label (e.g. 'Graded Score').", max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Decimal'), ('boolean', 'Boolean'), ('choice', 'Choice'), ('date', 'Date')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, help_text='Used for choice fields only.', null=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='assets.customassettype')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('asset_type', 'name')},
            },
        ),
    ]
