# Generated by Django 6.0.1 on 2026-01-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_rename_last_updated_customasset_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customassetfield',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customassetfield',
            name='name',
            field=models.CharField(editable=False, help_text="Internal field name (e.g. 'grade', 'card_type').", max_length=100),
        ),
        migrations.AddConstraint(
            model_name='customassetfield',
            constraint=models.UniqueConstraint(fields=('asset_type', 'name'), name='unique_custom_field_name_per_type'),
        ),
        migrations.AddConstraint(
            model_name='customassetfield',
            constraint=models.UniqueConstraint(fields=('asset_type', 'label'), name='unique_custom_field_label_per_type'),
        ),
    ]
