# Generated by Django 6.0 on 2025-12-09 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_exchange'),
        ('fx', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='If null → system exchange; If set → user-created exchange.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('code',), name='unique_system_exchange_code'),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('code', 'owner'), name='unique_user_exchange_code_per_owner'),
        ),
    ]
