# Generated by Django 5.2.6 on 2025-10-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_marketdatacache_remove_equitydetail_aum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equitydetail',
            name='dividend_frequency',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='dividend_per_share',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='ex_dividend_date',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='pb_ratio',
        ),
        migrations.RemoveField(
            model_name='equitydetail',
            name='pe_ratio',
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='avg_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='year_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='year_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
