# Generated by Django 5.2.6 on 2025-10-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_equitydetail_dividend_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdatacache',
            options={'verbose_name': 'Market Data Cache', 'verbose_name_plural': 'Market Data Cache'},
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='coupon_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='dividend_per_share',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='metal_purity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='yield_to_maturity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
