# Generated by Django 6.0 on 2025-12-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_exchange_owner_exchange_unique_system_exchange_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='delay',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='symbol_suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
