# Generated by Django 6.0.1 on 2026-01-16 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_customassetfield_unique_together_and_more'),
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customasset',
            name='attributes',
            field=models.JSONField(default=dict, help_text='Schema-defined attributes.'),
        ),
        migrations.AlterField(
            model_name='customasset',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_assets', to='fx.fxcurrency'),
        ),
        migrations.AlterField(
            model_name='customasset',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customassetfield',
            name='choices',
            field=models.JSONField(blank=True, help_text='Required for choice fields only.', null=True),
        ),
        migrations.AlterField(
            model_name='customassetfield',
            name='label',
            field=models.CharField(help_text="Display label (e.g. 'Grade').", max_length=100),
        ),
        migrations.AlterField(
            model_name='customassetfield',
            name='name',
            field=models.CharField(editable=False, help_text='Internal field name (auto-generated).', max_length=100),
        ),
    ]
