# Generated by Django 6.0.1 on 2026-01-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_customasset_attributes_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customasset',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='customasset',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customasset',
            name='custom_type',
        ),
        migrations.RemoveField(
            model_name='customasset',
            name='owner',
        ),
        migrations.RemoveConstraint(
            model_name='customassetfield',
            name='unique_custom_field_name_per_type',
        ),
        migrations.RemoveConstraint(
            model_name='customassetfield',
            name='unique_custom_field_label_per_type',
        ),
        migrations.AlterUniqueTogether(
            name='customassettype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customassettype',
            name='created_by',
        ),
        migrations.AddField(
            model_name='assettype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Null = system-defined asset type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='slug',
            field=models.SlugField(editable=False, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_asset_type_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(fields=('created_by', 'slug'), name='unique_asset_Type_slug_per_user'),
        ),
        migrations.DeleteModel(
            name='CustomAsset',
        ),
        migrations.DeleteModel(
            name='CustomAssetField',
        ),
        migrations.DeleteModel(
            name='CustomAssetType',
        ),
    ]
