# Generated by Django 6.0 on 2025-12-17 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_bonddetail_uniq_bond_isin_and_more'),
        ('fx', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source', models.CharField(default='FMP', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_price', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='EquityPriceExtension',
            fields=[
                ('asset_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equity_extension', serialize=False, to='assets.assetprice')),
                ('change', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('avg_volume', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('symbol_suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('delay', models.CharField(blank=True, max_length=50, null=True)),
                ('is_system', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='fx.country')),
                ('owner', models.ForeignKey(blank=True, help_text='If null → system exchange; If set → user-created exchange.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable industry name (e.g., 'Semiconductors').", max_length=150)),
                ('slug', models.SlugField(help_text="URL-safe unique slug (e.g., 'semiconductors').", max_length=150)),
                ('is_system', models.BooleanField(default=False, help_text='True if this industry comes from FMP and is global for all users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='NULL for system industries. Set to user for custom industries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_industries', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=150)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_sectors', to='users.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquityProfile',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equity_profile', serialize=False, to='assets.asset')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('last_dividend', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('ipo_date', models.DateField(blank=True, null=True)),
                ('is_etf', models.BooleanField(default=False)),
                ('is_adr', models.BooleanField(default=False)),
                ('is_fund', models.BooleanField(default=False)),
                ('is_actively_trading', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx.country')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.exchange')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.industry')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.sector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('code',), name='unique_system_exchange_code'),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('code', 'owner'), name='unique_user_exchange_code_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='unique_system_industry_slug'),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('slug', 'owner'), name='unique_user_industry_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='unique_system_sector_slug'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('slug', 'owner'), name='unique_user_sector_slug_per_owner'),
        ),
    ]
