# Generated by Django 6.0.1 on 2026-01-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_customasset_asset_remove_customasset_currency_and_more'),
        ('fx', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAsset',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='custom', serialize=False, to='assets.asset')),
                ('name', models.CharField(help_text="User-defined name (e.g. 'Charizard PSA 10').", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_assets', to='fx.fxcurrency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_assets', to='users.profile')),
            ],
        ),
    ]
