# Generated by Django 6.0 on 2025-12-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_assetprice_equitypriceextension_exchange_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityDividendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('record_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('declaration_date', models.DateField(blank=True, null=True)),
                ('dividend', models.DecimalField(decimal_places=6, max_digits=20)),
                ('adj_dividend', models.DecimalField(blank=True, decimal_places=6, help_text='Split-adjusted dividend as reported by provider', max_digits=20, null=True)),
                ('yield_value', models.FloatField(blank=True, help_text='Yield value as reported by provider (not used for calculations)', null=True)),
                ('frequency', models.CharField(blank=True, help_text='Raw dividend frequency string as returned by provider', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_events', to='assets.asset')),
            ],
            options={
                'ordering': ['-ex_date'],
                'indexes': [models.Index(fields=['asset', 'ex_date'], name='assets_equi_asset_i_6aeb9a_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'ex_date'), name='uniq_equity_dividend_event')],
            },
        ),
    ]
