# Generated by Django 6.0 on 2025-12-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_equitydividendevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityDividendExtension',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dividend_extension', serialize=False, to='assets.asset')),
                ('trailing_dividend_12m', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('forward_dividend', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
