# Generated by Django 6.0 on 2025-12-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_equitydividendextension'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assetidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('asset',), name='uniq_primary_identifier_per_asset'),
        ),
    ]
