# Generated by Django 6.0.1 on 2026-01-07 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_assetidentifier_uniq_primary_identifier_per_asset'),
        ('fx', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetidentifier',
            name='uniq_primary_identifier_per_asset',
        ),
        migrations.RemoveIndex(
            model_name='assetidentifier',
            name='assets_asse_asset_i_a4c149_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assetidentifier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Owner of this asset if is_custom=True. NULL for system assets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_assets', to='users.profile'),
        ),
        migrations.AddField(
            model_name='equitydividendextension',
            name='forward_yield',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equitydividendextension',
            name='trailing_yield',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_custom'], name='assets_asse_is_cust_0ea0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['created_by'], name='assets_asse_created_e62c76_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetidentifier',
            constraint=models.UniqueConstraint(fields=('asset', 'id_type'), name='uniq_identifier_type_per_asset'),
        ),
        migrations.RemoveField(
            model_name='assetidentifier',
            name='is_primary',
        ),
    ]
