# Generated by Django 6.0.1 on 2026-01-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_remove_assetidentifier_uniq_primary_identifier_per_asset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='industry',
            name='unique_system_industry_slug',
        ),
        migrations.RemoveConstraint(
            model_name='industry',
            name='unique_user_industry_slug_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='unique_system_sector_slug',
        ),
        migrations.RemoveConstraint(
            model_name='sector',
            name='unique_user_sector_slug_per_owner',
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(help_text="Human-readable industry name (e.g., 'Semiconductors').", max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.SlugField(help_text='URL-safe unique slug.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='industry',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='owner',
        ),
    ]
