# Generated by Django 6.0.1 on 2026-01-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_industry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityprofile',
            name='identity_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
