# Generated by Django 5.2.3 on 2025-06-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPortfolioSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='portfolios.stockportfolio')),
            ],
            options={
                'unique_together': {('stock_portfolio', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockPortfolioSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('decimal', 'Number'), ('string', 'Text'), ('date', 'Date'), ('url', 'URL')], max_length=10)),
                ('source', models.CharField(choices=[('asset', 'Asset'), ('holding', 'Holding'), ('calculated', 'Calculated'), ('custom', 'Custom')], max_length=20)),
                ('decimal_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('source_field', models.CharField(blank=True, choices=[], max_length=100)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.stockportfolioschema')),
            ],
            options={
                'unique_together': {('schema', 'title')},
            },
        ),
        migrations.CreateModel(
            name='StockPortfolioSCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='schemas.stockportfoliosc')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_values', to='assets.stockholding')),
            ],
            options={
                'unique_together': {('column', 'holding')},
            },
        ),
    ]
