# Generated by Django 5.2.1 on 2025-05-13 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_content_type', models.ForeignKey(limit_choices_to={'app_label': 'stock_portfolio', 'model__in': ['stockportfolio']}, on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Schema',
                'unique_together': {('portfolio_content_type', 'portfolio_object_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('decimal', 'Number'), ('string', 'Holding'), ('date', 'Date'), ('url', 'URL')], max_length=10)),
                ('source', models.CharField(choices=[('asset', 'Asset'), ('holding', 'Holding'), ('calculated', 'Calculated'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, max_length=100, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.schema')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='schemas.schemacolumn')),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label__in': ['stock_portfolio', 'crypto']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'column')},
            },
        ),
    ]
