# Generated by Django 5.2.1 on 2025-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schema',
            options={},
        ),
        migrations.RenameField(
            model_name='schema',
            old_name='portfolio_content_type',
            new_name='sub_portfolio_content_type',
        ),
        migrations.RenameField(
            model_name='schema',
            old_name='portfolio_object_id',
            new_name='sub_portfolio_object_id',
        ),
        migrations.AlterUniqueTogether(
            name='schema',
            unique_together={('sub_portfolio_content_type', 'sub_portfolio_object_id', 'name')},
        ),
        migrations.AddField(
            model_name='schema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
