# Generated by Django 5.2.1 on 2025-05-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schemas', '0002_alter_schema_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumnvalue',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['stock_portfolio'], 'model__in': ['stockholding']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
