# Generated by Django 5.2.1 on 2025-05-14 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schemas', '0003_alter_schemacolumnvalue_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumnvalue',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'stock_portfolio', 'model': 'stockholding'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
