# Generated by Django 5.2.1 on 2025-05-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_alter_schemacolumnvalue_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='data_type',
            field=models.CharField(choices=[('decimal', 'Number'), ('string', 'Text'), ('date', 'Date'), ('url', 'URL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='source_field',
            field=models.CharField(max_length=100),
        ),
    ]
