# Generated by Django 5.2.1 on 2025-05-16 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPortfolioSchemaColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockPortfolioSchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('decimal', 'Number'), ('string', 'Text'), ('date', 'Date'), ('url', 'URL')], max_length=10)),
                ('source', models.CharField(choices=[('asset', 'Asset'), ('holding', 'Holding'), ('calculated', 'Calculated'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(max_length=100)),
                ('formula', models.TextField(blank=True, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='stock_portfolio.stockportfolioschema')),
            ],
            options={
                'unique_together': {('schema', 'name')},
            },
        ),
    ]
