# Generated by Django 5.2 on 2025-05-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='default_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_portfolios', to='stock_portfolio.schema'),
        ),
    ]
