# Generated by Django 5.2.1 on 2025-05-20 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0001_initial'),
        ('stocks', '0002_delete_customstock_delete_invalidticker_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashbalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cashbalance',
            name='account',
        ),
        migrations.RemoveConstraint(
            model_name='stockholding',
            name='unique_holding',
        ),
        migrations.RemoveField(
            model_name='stockholding',
            name='account_content_type',
        ),
        migrations.RemoveField(
            model_name='stockholding',
            name='account_object_id',
        ),
        migrations.RemoveField(
            model_name='stockholding',
            name='asset_content_type',
        ),
        migrations.RemoveField(
            model_name='stockholding',
            name='asset_object_id',
        ),
        migrations.AddField(
            model_name='stockholding',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='stocks.stock'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CashBalance',
        ),
    ]
