# Generated by Django 5.2.1 on 2025-05-13 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('stock_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='investment_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='portfolio.investmenttheme'),
        ),
    ]
