# Generated by Django 5.2 on 2025-04-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investmenttheme'),
        ('stock_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_portfolios', to='portfolio.portfolio'),
        ),
    ]
