# Generated by Django 5.2.1 on 2025-05-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedaccount',
            name='use_default_schema',
        ),
        migrations.RemoveField(
            model_name='selfmanagedaccount',
            name='use_default_schema',
        ),
    ]
