# Generated by Django 5.2 on 2025-04-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0002_alter_stockportfolio_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stock_portfolio.stockportfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelfManagedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stock_portfolio.stockportfolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
