# Generated by Django 5.2.1 on 2025-05-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0002_remove_managedaccount_use_default_schema_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockportfolioschemacolumn',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='stockportfolioschemacolumn',
            unique_together={('schema', 'source_field'), ('schema', 'title')},
        ),
    ]
