# Generated by Django 5.2.1 on 2025-05-13 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('portfolio', '0001_initial'),
        ('stock_portfolio', '0002_stockholding_investment_theme'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockholding',
            name='unique_holding',
        ),
        migrations.RemoveField(
            model_name='stockholding',
            name='portfolio_content_type',
        ),
        migrations.RemoveField(
            model_name='stockholding',
            name='portfolio_object_id',
        ),
        migrations.AlterField(
            model_name='selfmanagedaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='stock_portfolio.stockportfolio'),
        ),
        migrations.AddConstraint(
            model_name='stockholding',
            constraint=models.UniqueConstraint(fields=('asset_content_type', 'asset_object_id', 'account_content_type', 'account_object_id'), name='unique_holding'),
        ),
    ]
