# Generated by Django 5.2 on 2025-05-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0002_alter_stockportfolio_default_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='is_default',
        ),
    ]
