# Generated by Django 5.2 on 2025-04-23 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0003_managedaccount_selfmanagedaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('long_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_etf', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('market', models.CharField(blank=True, max_length=50, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('day_high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('day_low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fifty_two_week_high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('fifty_two_week_low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('average_volume', models.BigIntegerField(blank=True, null=True)),
                ('average_volume_10d', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('forward_pe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_to_book', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('payout_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ex_dividend_date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('full_time_employees', models.IntegerField(blank=True, null=True)),
                ('long_business_summary', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_portfolio.stock')),
                ('stock_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_portfolio.selfmanagedaccount')),
            ],
            options={
                'unique_together': {('stock_account', 'ticker')},
            },
        ),
    ]
