# Generated by Django 5.2 on 2025-05-07 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0003_remove_schema_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedaccount',
            name='active_schema',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='default_schema',
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='default_managed_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_managed_accounts', to='stock_portfolio.schema'),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='default_self_managed_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_self_managed_accounts', to='stock_portfolio.schema'),
        ),
        migrations.AlterField(
            model_name='selfmanagedaccount',
            name='active_schema',
            field=models.ForeignKey(blank=True, help_text='Schema used to display stock holdings for this account.', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_portfolio.schema'),
        ),
    ]
