# Generated by Django 5.2.1 on 2025-05-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0003_rename_name_stockportfolioschemacolumn_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockportfolioschemacolumn',
            name='is_deletable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stockportfolioschemacolumn',
            name='source_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
