# Generated by Django 5.2 on 2025-04-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0004_stock_stockholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quote_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
