# Generated by Django 5.2 on 2025-05-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0004_remove_managedaccount_active_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedaccount',
            name='use_default_schema',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='selfmanagedaccount',
            name='use_default_schema',
            field=models.BooleanField(default=True),
        ),
    ]
