# Generated by Django 5.2 on 2025-04-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investmenttheme'),
        ('stock_portfolio', '0005_stock_quote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_etf',
        ),
        migrations.AddField(
            model_name='stock',
            name='investment_theme',
            field=models.ManyToManyField(blank=True, related_name='assets', to='portfolio.investmenttheme'),
        ),
    ]
