# Generated by Django 5.2.1 on 2025-05-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0005_alter_stockportfolioschemacolumn_source_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockportfolioschemacolumn',
            unique_together={('schema', 'title')},
        ),
    ]
