# Generated by Django 5.2 on 2025-05-08 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0005_managedaccount_use_default_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='stock_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockholdings', to='stock_portfolio.selfmanagedaccount'),
        ),
    ]
