# Generated by Django 5.2.1 on 2025-05-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0006_alter_stockportfolioschemacolumn_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_accounts', to='stock_portfolio.stockportfolio'),
        ),
        migrations.AlterField(
            model_name='selfmanagedaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_managed_accounts', to='stock_portfolio.stockportfolio'),
        ),
    ]
