# Generated by Django 5.2 on 2025-04-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0006_remove_stock_is_etf_stock_investment_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
