# Generated by Django 5.2 on 2025-04-25 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0007_stock_is_custom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockholding',
            unique_together={('stock_account', 'stock')},
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='stock_portfolio.stockportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('decimal', 'Decimal'), ('integer', 'Integer'), ('string', 'String'), ('date', 'Date'), ('url', 'URL')], max_length=10)),
                ('source', models.CharField(choices=[('stock', 'Stock'), ('holding', 'StockHolding'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, max_length=100, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='stock_portfolio.schema')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockholding',
            name='ticker',
        ),
        migrations.CreateModel(
            name='SchemaColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='stock_portfolio.schemacolumn')),
                ('stock_holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_values', to='stock_portfolio.stockholding')),
            ],
            options={
                'unique_together': {('stock_holding', 'column')},
            },
        ),
    ]
