# Generated by Django 5.2.1 on 2025-05-27 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_currency'),
        ('stock_portfolio', '0007_alter_managedaccount_stock_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockportfolio', to='portfolio.portfolio'),
        ),
    ]
