# Generated by Django 5.2 on 2025-04-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0008_alter_stockholding_unique_together_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='data_type',
            field=models.CharField(choices=[('decimal', 'Number'), ('string', 'String'), ('date', 'Date'), ('url', 'URL')], max_length=10),
        ),
    ]
