# Generated by Django 5.2.2 on 2025-06-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0008_alter_stockportfolio_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedaccount',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='selfmanagedaccount',
            name='currency',
        ),
    ]
