# Generated by Django 5.2.2 on 2025-06-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0009_remove_managedaccount_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolioschemacolumn',
            name='source_field',
            field=models.CharField(blank=True, choices=[('ticker', 'Ticker'), ('price', 'Price'), ('name', 'Name'), ('quantity', 'Quantity'), ('purchase_price', 'Purchase Price'), ('holding.ticker', 'Holding.Ticker'), ('current_value', 'Current Value')], max_length=100),
        ),
    ]
