# Generated by Django 5.2 on 2025-05-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0010_managedaccount_account_type_managedaccount_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemacolumn',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='source',
            field=models.CharField(choices=[('stock', 'Stock'), ('holding', 'StockHolding'), ('calculated', 'Calculated'), ('custom', 'Custom')], max_length=20),
        ),
    ]
