# Generated by Django 5.2.2 on 2025-06-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0010_alter_stockportfolioschemacolumn_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolioschemacolumn',
            name='source_field',
            field=models.CharField(blank=True, choices=[('ticker', 'Ticker'), ('price', 'Price'), ('name', 'Name'), ('quantity', 'Quantity'), ('purchase_price', 'Purchase Price'), ('holding.ticker', 'Holding.Ticker'), ('current_value', 'Current Value'), ('value_in_profile_currency', 'Value In Profile Currency'), ('unrealized_gain', 'Unrealized Gain')], max_length=100),
        ),
    ]
