# Generated by Django 5.2.2 on 2025-06-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0011_alter_stockportfolioschemacolumn_source_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfmanagedaccount',
            name='current_value_fx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stockportfolioschemacolumn',
            name='source_field',
            field=models.CharField(blank=True, choices=[('ticker', 'Ticker'), ('price', 'Price'), ('name', 'Name'), ('quantity', 'Quantity'), ('purchase_price', 'Purchase Price'), ('holding.ticker', 'Holding.Ticker'), ('current_value', 'Current Value'), ('value_in_profile_fx', 'Value In Profile Fx'), ('unrealized_gain', 'Unrealized Gain'), ('unrealized_gain_profile_fx', 'Unrealized Gain Profile Fx')], max_length=100),
        ),
    ]
