# Generated by Django 5.2 on 2025-05-06 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0011_schemacolumn_formula_alter_schemacolumn_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfmanagedaccount',
            name='stock_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_managed_accounts', to='stock_portfolio.stockportfolio'),
        ),
    ]
