# Generated by Django 5.2.2 on 2025-06-11 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0012_selfmanagedaccount_current_value_fx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfmanagedaccount',
            name='current_value_fx',
        ),
    ]
