# Generated by Django 5.2.2 on 2025-06-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_portfolio', '0014_managedaccount_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='managedaccount',
            unique_together={('stock_portfolio', 'name')},
        ),
    ]
