# Generated by Django 6.0.2 on 2026-02-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Portfolio', max_length=100)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('client', 'Client')], default='personal', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
