# Generated by Django 5.2.5 on 2025-08-29 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='users.profile'),
        ),
        migrations.AddField(
            model_name='metalportfolio',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metalportfolio', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='customportfolio',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_portfolios', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='cryptoportfolio',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cryptoportfolio', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockportfolio', to='portfolios.portfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='customportfolio',
            unique_together={('portfolio', 'slug')},
        ),
    ]
