# Generated by Django 6.0.2 on 2026-02-17 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='profiles.profile'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['profile', 'kind'], name='portfolios__profile_61b397_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('profile',), name='unique_main_portfolio_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='unique_portfolio_name_prt_profile'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client_name__isnull', True), ('kind', 'personal')), models.Q(('client_name', ''), ('kind', 'personal')), models.Q(('client_name__isnull', False), ('kind', 'client'), models.Q(('client_name', ''), _negated=True)), _connector='OR'), name='client_name_required_for_client_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('is_main', False), models.Q(('is_main', True), ('kind', 'personal'), models.Q(('client_name__isnull', True), ('client_name', ''), _connector='OR')), _connector='OR'), name='main_portfolio_must_be_personal'),
        ),
    ]
