# Generated by Django 5.2.6 on 2025-09-05 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_cryptoaccount_crypto_portfolio_and_more'),
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customportfolio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customportfolio',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='metalportfolio',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='portfolio',
        ),
        migrations.CreateModel(
            name='SubPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('metal', 'Metal'), ('custom', 'Custom')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subportfolios', to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'type', 'slug')},
            },
        ),
        migrations.DeleteModel(
            name='CryptoPortfolio',
        ),
        migrations.DeleteModel(
            name='CustomPortfolio',
        ),
        migrations.DeleteModel(
            name='MetalPortfolio',
        ),
        migrations.DeleteModel(
            name='StockPortfolio',
        ),
    ]
