# Generated by Django 5.2.5 on 2025-08-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='managed_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_managed_schema', to='schemas.schema'),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='self_managed_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_self_schema', to='schemas.schema'),
        ),
    ]
