# Generated by Django 5.2.6 on 2025-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subportfolio',
            name='type',
            field=models.CharField(choices=[('stock', 'Stocks'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('custom', 'Custom')], max_length=50),
        ),
    ]
