# Generated by Codex on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="client_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="kind",
            field=models.CharField(
                choices=[("personal", "Personal"), ("client", "Client")],
                default="personal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to="profiles.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["profile", "kind"], name="portfolio_profile_kind_idx"),
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(("kind", "personal"), ("client_name__isnull", True))
                    | models.Q(("kind", "personal"), ("client_name", ""))
                    | (
                        models.Q(("kind", "client"), ("client_name__isnull", False))
                        & ~models.Q(("client_name", ""))
                    )
                ),
                name="client_name_required_for_client_portfolio",
            ),
        ),
    ]
