# Generated by Django 5.2.6 on 2025-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subportfolio',
            name='type',
            field=models.CharField(choices=[('equity', 'Equities'), ('crypto', 'Crypto'), ('metal', 'Metals'), ('bond', 'Bonds'), ('real_estate', 'Real Estate'), ('custom', 'Custom')], max_length=50),
        ),
    ]
