# Generated by Django 5.2.6 on 2025-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_customportfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subportfolio',
            name='type',
            field=models.CharField(choices=[('stock', 'Stock Portfolio'), ('crypto', 'Crypto Portfolio'), ('metal', 'Precious Metal Portfolio'), ('custom', 'Custom Portfolio')], max_length=50),
        ),
    ]
