# Generated by Django 6.0.2 on 2026-02-19 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_delete_realestatecashflow'),
        ('fx', '0001_initial'),
        ('portfolios', '0004_remove_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('profile_currency', 'Profile Currency'), ('currency', 'Currency'), ('asset_units', 'Asset Units')], max_length=30)),
                ('reference_code', models.CharField(blank=True, help_text='External identifier used to resolve an asset (e.g. BTC, AAPL, GCUSD).', max_length=30, null=True)),
                ('unit_label', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_denominations', to='assets.asset')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_denominations', to='fx.fxcurrency')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['display_order', 'key'],
                'indexes': [models.Index(fields=['portfolio', 'is_active', 'display_order'], name='portfolios__portfol_3ae657_idx')],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'key'), name='uniq_portfolio_denomination_key')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value_identifier', models.SlugField(default='current_value', max_length=100)),
                ('profile_currency_code', models.CharField(max_length=3)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('denominations', models.JSONField(blank=True, default=list)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_snapshots', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['portfolio', '-captured_at'], name='portfolios__portfol_d4a540_idx')],
            },
        ),
    ]
