# schemas/config/schema_templates/equity_template.py

EQUITY_TEMPLATE_CONFIG = {
    "account_type": "equity_self",
    "name": "Equity Schema Template",
    "description": "Default schema template for equity portfolios, covering tradable stock assets and holdings.",

    "columns": [
        # --- Identification ---
        {
            "title": "Symbol",
            "identifier": "symbol",
            "data_type": "string",
            "source": "asset",
            "source_field": "primary_identifier__value",
            "is_system": True,
            "is_editable": False,
            "display_order": 1,
        },
        {
            "title": "Name",
            "identifier": "name",
            "data_type": "string",
            "source": "asset",
            "source_field": "name",
            "is_system": True,
            "is_editable": False,
            "display_order": 2,
        },
        {
            "title": "Currency",
            "identifier": "currency",
            "data_type": "string",
            "source": "asset",
            "source_field": "currency",
            "is_system": True,
            "is_editable": False,
            "display_order": 3,
        },

        # --- Market Data ---
        {
            "title": "Last Price",
            "identifier": "last_price",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__last_price",
            "is_system": True,
            "is_editable": False,
            "display_order": 4,
        },
        {
            "title": "Market Cap",
            "identifier": "market_cap",
            "data_type": "integer",
            "source": "asset",
            "source_field": "market_data__market_cap",
            "is_system": True,
            "is_editable": False,
            "display_order": 5,
        },
        {
            "title": "P/E Ratio",
            "identifier": "pe_ratio",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__pe_ratio",
            "is_system": True,
            "is_editable": False,
            "display_order": 6,
        },
        {
            "title": "EPS",
            "identifier": "eps",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__eps",
            "is_system": True,
            "is_editable": False,
            "display_order": 7,
        },
        {
            "title": "Dividend Yield",
            "identifier": "dividend_yield",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__dividend_yield",
            "is_system": True,
            "is_editable": False,
            "display_order": 8,
        },
        {
            "title": "Dividend Per Share",
            "identifier": "dividend_per_share",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__dividend_per_share",
            "is_system": True,
            "is_editable": False,
            "display_order": 9,
        },

        # --- Holding Data ---
        {
            "title": "Quantity",
            "identifier": "quantity",
            "data_type": "decimal",
            "source": "holding",
            "source_field": "quantity",
            "is_system": True,
            "is_editable": True,
            "display_order": 10,
        },
        {
            "title": "Purchase Price",
            "identifier": "purchase_price",
            "data_type": "decimal",
            "source": "holding",
            "source_field": "purchase_price",
            "is_system": True,
            "is_editable": True,
            "display_order": 11,
        },
        {
            "title": "Purchase Date",
            "identifier": "purchase_date",
            "data_type": "date",
            "source": "holding",
            "source_field": "purchase_date",
            "is_system": True,
            "is_editable": True,
            "display_order": 12,
        },
    ],
}
