EQUITY_TEMPLATE_CONFIG = {
    "account_type": "equity_self",
    "name": "Equity Schema Template",
    "description": "Default schema template for equity portfolios, covering tradable stock assets and holdings.",

    "columns": [
        # --- Identification (Default Columns) ---
        {
            "title": "Symbol",
            "identifier": "symbol",
            "data_type": "string",
            "source": "asset",
            "source_field": "primary_identifier__value",
            "is_system": True,
            "is_editable": False,
            "is_default": True,
            "display_order": 1,
        },
        {
            "title": "Name",
            "identifier": "name",
            "data_type": "string",
            "source": "asset",
            "source_field": "name",
            "is_system": True,
            "is_editable": False,
            "is_default": True,
            "display_order": 2,
        },
        {
            "title": "Currency",
            "identifier": "currency",
            "data_type": "string",
            "source": "asset",
            "source_field": "currency",
            "is_system": True,
            "is_editable": False,
            "is_default": True,
            "display_order": 3,
        },

        # --- Holding Data (Default Columns) ---
        {
            "title": "Purchase Price",
            "identifier": "purchase_price",
            "data_type": "decimal",
            "source": "holding",
            "source_field": "purchase_price",
            "is_system": True,
            "is_editable": True,
            "is_default": True,
            "display_order": 4,
        },
        {
            "title": "Quantity",
            "identifier": "quantity",
            "data_type": "decimal",
            "source": "holding",
            "source_field": "quantity",
            "is_system": True,
            "is_editable": True,
            "is_default": True,
            "display_order": 5,
        },

        # --- Market Data (Default Column) ---
        {
            "title": "Last Price",
            "identifier": "last_price",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__last_price",
            "is_system": True,
            "is_editable": False,
            "is_default": True,
            "display_order": 6,
        },

        # --- Non-Default Available Columns (for “Add Column” UI) ---
        {
            "title": "Market Cap",
            "identifier": "market_cap",
            "data_type": "integer",
            "source": "asset",
            "source_field": "market_data__market_cap",
            "is_system": True,
            "is_editable": False,
            "is_default": False,
        },
        {
            "title": "P/E Ratio",
            "identifier": "pe_ratio",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__pe_ratio",
            "is_system": True,
            "is_editable": False,
            "is_default": False,
        },
        {
            "title": "EPS",
            "identifier": "eps",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__eps",
            "is_system": True,
            "is_editable": False,
            "is_default": False,
        },
        {
            "title": "Dividend Yield",
            "identifier": "dividend_yield",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__dividend_yield",
            "is_system": True,
            "is_editable": False,
            "is_default": False,
        },
        {
            "title": "Dividend Per Share",
            "identifier": "dividend_per_share",
            "data_type": "decimal",
            "source": "asset",
            "source_field": "market_data__dividend_per_share",
            "is_system": True,
            "is_editable": False,
            "is_default": False,
        },
        {
            "title": "Purchase Date",
            "identifier": "purchase_date",
            "data_type": "date",
            "source": "holding",
            "source_field": "purchase_date",
            "is_system": True,
            "is_editable": True,
            "is_default": False,
        },
    ],
}
