# Generated by Django 5.2.1 on 2025-05-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
