# Generated by Django 5.1.6 on 2025-03-05 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_role_profile_account_type'),
        ('portfolio', '0002_remove_portfolio_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Individual Portfolio', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(limit_choices_to={'account_type': 'individual'}, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
