# Generated by Django 5.1.7 on 2025-03-14 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_country_profile_birth_date_and_more'),
        ('portfolio', '0002_remove_individualportfolio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualportfolio',
            name='profile',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='core.profile')),
            ],
        ),
    ]
