# Generated by Django 5.1.6 on 2025-03-07 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_account_type'),
        ('portfolio', '0003_individualportfolio_delete_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualportfolio',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_portfolio', to='core.profile'),
        ),
    ]
