# Generated by Django 5.1.7 on 2025-03-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_individualportfolio_profile_portfolio'),
        ('securities', '0006_alter_stockportfolio_individual_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndividualPortfolio',
        ),
    ]
