# Generated by Django 6.0.3 on 2026-04-07 00:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquityDirectorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='fmp', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='integration_provide_7cc3c6_idx'), models.Index(fields=['created_at'], name='integration_created_945fbb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('provider',), name='uniq_active_equity_directory_snapshot_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='EquityDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('is_actively_traded', models.BooleanField(default=False)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='integrations.equitydirectorysnapshot')),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['snapshot', 'symbol'], name='integration_snapsho_4206ba_idx'), models.Index(fields=['snapshot', 'is_actively_traded'], name='integration_snapsho_7cfb93_idx'), models.Index(fields=['name'], name='integration_name_258e7c_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'symbol'), name='uniq_equity_directory_entry_per_snapshot_symbol')],
            },
        ),
    ]
