# Generated by Django 6.0.3 on 2026-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveEquityListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='fmp', max_length=50)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.RemoveIndex(
            model_name='equitydirectoryentry',
            name='integration_snapsho_4206ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='equitydirectoryentry',
            name='integration_snapsho_7cfb93_idx',
        ),
        migrations.RemoveIndex(
            model_name='equitydirectoryentry',
            name='integration_name_258e7c_idx',
        ),
        migrations.RemoveConstraint(
            model_name='equitydirectoryentry',
            name='uniq_equity_directory_entry_per_snapshot_symbol',
        ),
        migrations.RemoveIndex(
            model_name='equitydirectorysnapshot',
            name='integration_provide_7cc3c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='equitydirectorysnapshot',
            name='integration_created_945fbb_idx',
        ),
        migrations.RemoveConstraint(
            model_name='equitydirectorysnapshot',
            name='uniq_active_equity_directory_snapshot_per_provider',
        ),
        migrations.AddIndex(
            model_name='activeequitylisting',
            index=models.Index(fields=['provider', 'symbol'], name='integration_provide_742266_idx'),
        ),
        migrations.AddIndex(
            model_name='activeequitylisting',
            index=models.Index(fields=['name'], name='integration_name_28f7f4_idx'),
        ),
        migrations.DeleteModel(
            name='EquityDirectoryEntry',
        ),
        migrations.DeleteModel(
            name='EquityDirectorySnapshot',
        ),
    ]
