# Generated by Django 6.0.3 on 2026-04-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_activeequitylisting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCommodityListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='fmp', max_length=50)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(blank=True, max_length=100)),
                ('trade_month', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['provider', 'symbol'], name='integration_provide_149af0_idx'), models.Index(fields=['name'], name='integration_name_d4ec6e_idx'), models.Index(fields=['exchange'], name='integration_exchang_96e7f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActiveCryptoListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='fmp', max_length=50)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('base_symbol', models.CharField(blank=True, max_length=20)),
                ('quote_currency', models.CharField(blank=True, max_length=10)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['provider', 'symbol'], name='integration_provide_f22dde_idx'), models.Index(fields=['base_symbol'], name='integration_base_sy_5ab461_idx'), models.Index(fields=['name'], name='integration_name_22c6ec_idx')],
            },
        ),
    ]
