# Generated by Django 6.0.3 on 2026-04-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_activecommoditylisting_activecryptolisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FXRateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='fmp', max_length=50)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('pair_symbol', models.CharField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=30)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('as_of', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['base_currency', 'quote_currency'],
                'indexes': [models.Index(fields=['provider', 'base_currency', 'quote_currency'], name='integration_provide_7967bf_idx'), models.Index(fields=['pair_symbol'], name='integration_pair_sy_8ff8a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'base_currency', 'quote_currency'), name='uniq_fx_rate_cache_per_provider_pair')],
            },
        ),
    ]
