# Generated by Django 5.2.8 on 2025-11-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FXCurrency',
            fields=[
                ('code', models.CharField(help_text='ISO-like currency code (derived from FX pairs)', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Human-readable currency name from FMP', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_from_rates', to='fx.fxcurrency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_to_rates', to='fx.fxcurrency')),
            ],
            options={
                'ordering': ['from_currency__code', 'to_currency__code'],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
