# Generated by Django 6.0.1 on 2026-01-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO-3166 alpha-2 country code (e.g., US, JP, DE).', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full English name (from pycountry, or fallback to code).', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Optional region grouping (e.g., Europe, APAC).', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FXCurrency',
            fields=[
                ('code', models.CharField(help_text='ISO-like currency code (derived from FX pairs)', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable currency name from FMP', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_from_rates', to='fx.fxcurrency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_to_rates', to='fx.fxcurrency')),
            ],
            options={
                'ordering': ['from_currency__code', 'to_currency__code'],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
