# Generated by Django 6.0.1 on 2026-01-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxcurrency',
            name='name',
            field=models.CharField(blank=True, help_text='Human-readable currency name from FMP', max_length=150, null=True),
        ),
    ]
