# Generated by Django 5.2.8 on 2025-11-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO-3166 alpha-2 country code (e.g., US, JP, DE).', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full English name (from pycountry, or fallback to code).', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Optional region grouping (e.g., Europe, APAC).', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
