# Generated by Django 6.0.1 on 2026-01-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx', '0002_alter_fxcurrency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fxcurrency',
            name='code',
            field=models.CharField(help_text='ISO-like currency code (derived from FX pairs)', max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fxcurrency',
            name='name',
            field=models.CharField(help_text='Human-readable currency name from FMP', max_length=150),
        ),
    ]
