from decimal import Decimal
from core.schema_config.utils import schema_field

CRYPTO_SCHEMA_CONFIG = {
    "asset": {
        # --- Identification ---
        "symbol": schema_field(
            title="Symbol",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=True,
            constraints={"character_limit": 10, "all_caps": True},
            display_order=1,
            subtype_labels=[],
        ),
        "name": schema_field(
            title="Name",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=True,
            constraints={"character_limit": 200},
            display_order=2,
            subtype_labels=[],
        ),
        "exchange": schema_field(
            title="Exchange",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "currency": schema_field(
            title="Quote Currency",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "decimals": schema_field(
            title="Decimals",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),

        # --- Market Data ---
        "last_price": schema_field(
            title="Last Price",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=True,
            constraints={"decimal_places": 6, "min": Decimal("0")},
            display_order=3,
            subtype_labels=[],
        ),
        "market_cap": schema_field(
            title="Market Cap",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=4,
            subtype_labels=[],
        ),
        "volume_24h": schema_field(
            title="24h Volume",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "circulating_supply": schema_field(
            title="Circulating Supply",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=5,
            subtype_labels=[],
        ),
        "total_supply": schema_field(
            title="Total Supply",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),

        # --- High/Low ---
        "day_high": schema_field(
            title="Day High",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "day_low": schema_field(
            title="Day Low",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "year_high": schema_field(
            title="Year High",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "year_low": schema_field(
            title="Year Low",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),

        # --- Open/Close ---
        "open_price": schema_field(
            title="Open Price",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "previous_close": schema_field(
            title="Previous Close",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "changes_percentage": schema_field(
            title="24h Change (%)",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=6,
            subtype_labels=[],
        ),

        # --- Metadata ---
        "description": schema_field(
            title="Description",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "website": schema_field(
            title="Website",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "logo_url": schema_field(
            title="Logo URL",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
    },

    "holding": {
        "quantity": schema_field(
            title="Quantity",
            data_type="decimal",
            is_editable=True,
            is_default=True,
            constraints={"decimal_places": 8},
            display_order=7,
            subtype_labels=[],
        ),
        "purchase_price": schema_field(
            title="Purchase Price",
            data_type="decimal",
            is_editable=True,
            is_default=True,
            constraints={"decimal_places": 2, "min": Decimal("0")},
            display_order=8,
            subtype_labels=[],
        ),
        "purchase_date": schema_field(
            title="Purchase Date",
            data_type="date",
            is_editable=True,
            is_default=True,
            display_order=9,
            subtype_labels=[],
        ),
    },

    "calculated": {
        "current_value_crypto_fx": schema_field(
            title="Current Value - Crypto FX",
            data_type="decimal",
            formula_key="current_value_crypto_fx",
            is_editable=False,
            is_default=True,
            constraints={"decimal_places": 2, "min": Decimal("0")},
            display_order=10,
            subtype_labels=[],
        ),
        "unrealized_gain": schema_field(
            title="Unrealized Gain",
            data_type="decimal",
            formula_key="unrealized_gain",
            is_editable=False,
            is_default=False,
            constraints={"decimal_places": 2},
            subtype_labels=[],
        ),
    },
}
