from decimal import Decimal
from core.schema_config.utils import schema_field


EQUITY_SCHEMA_CONFIG = {
    "asset": {
        # --- Identification ---
        "symbol": schema_field(
            title="Symbol",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=True,
            constraints={"character_limit": 10, "all_caps": True},
            display_order=1,
            subtype_labels=[],
        ),
        "name": schema_field(
            title="Name",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=True,
            constraints={"character_limit": 200},
            display_order=2,
            subtype_labels=[],
        ),
        "exchange": schema_field(
            title="Exchange",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=3,
            subtype_labels=[],
        ),
        "exchange_full_name": schema_field(
            title="Exchange (Full Name)",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "currency": schema_field(
            title="Currency",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=True,
            constraints={
                "character_limit": 3,
                "character_minimum": 3,
                "all_caps": True,
            },
            display_order=4,
            subtype_labels=[],
        ),
        "country": schema_field(
            title="Country",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "cusip": schema_field(
            title="CUSIP",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "isin": schema_field(
            title="ISIN",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "ipo_date": schema_field(
            title="IPO Date",
            data_type="date",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),

        # --- Classification ---
        "sector": schema_field(
            title="Sector",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=5,
            subtype_labels=[],
        ),
        "industry": schema_field(
            title="Industry",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=6,
            subtype_labels=[],
        ),
        "is_etf": schema_field(
            title="ETF",
            data_type="boolean",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["etf"],
        ),
        "is_adr": schema_field(
            title="ADR",
            data_type="boolean",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["adr"],
        ),
        "is_mutual_fund": schema_field(
            title="Mutual Fund",
            data_type="boolean",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["mutual_fund"],
        ),

        # --- Market Data ---
        "last_price": schema_field(
            title="Last Price",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=True,
            constraints={"decimal_places": 2, "min": Decimal("0")},
            display_order=7,
            subtype_labels=[],
        ),
        "open_price": schema_field(
            title="Open Price",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "high_price": schema_field(
            title="High Price",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "low_price": schema_field(
            title="Low Price",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "previous_close_price": schema_field(
            title="Previous Close",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "volume": schema_field(
            title="Volume",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=8,
            subtype_labels=[],
        ),
        "average_volume": schema_field(
            title="Average Volume",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "market_cap": schema_field(
            title="Market Cap",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=9,
            subtype_labels=[],
        ),
        "shares_outstanding": schema_field(
            title="Shares Outstanding",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "beta": schema_field(
            title="Beta",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),

        # --- Valuation Ratios ---
        "eps": schema_field(
            title="EPS",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "pe_ratio": schema_field(
            title="P/E Ratio",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=10,
            subtype_labels=[],
        ),
        "pb_ratio": schema_field(
            title="P/B Ratio",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "ps_ratio": schema_field(
            title="P/S Ratio",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "peg_ratio": schema_field(
            title="PEG Ratio",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),

        # --- Dividend Info ---
        "dividend_per_share": schema_field(
            title="Dividend Per Share",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "dividend_yield": schema_field(
            title="Dividend Yield",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=True,
            display_order=11,
            subtype_labels=[],
        ),
        "dividend_frequency": schema_field(
            title="Dividend Frequency",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "ex_dividend_date": schema_field(
            title="Ex-Dividend Date",
            data_type="date",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "dividend_payout_ratio": schema_field(
            title="Dividend Payout Ratio",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),

        # --- Mutual Fund Specific ---
        "nav": schema_field(
            title="NAV",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["mutual_fund"],
        ),
        "expense_ratio": schema_field(
            title="Expense Ratio",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["mutual_fund"],
        ),
        "fund_family": schema_field(
            title="Fund Family",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["mutual_fund"],
        ),
        "fund_category": schema_field(
            title="Fund Category",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["mutual_fund"],
        ),
        "inception_date": schema_field(
            title="Inception Date",
            data_type="date",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["mutual_fund"],
        ),
        "total_assets": schema_field(
            title="Total Assets",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["mutual_fund"],
        ),
        "turnover_ratio": schema_field(
            title="Turnover Ratio",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["mutual_fund"],
        ),

        # --- ETF Specific ---
        "underlying_index": schema_field(
            title="Underlying Index",
            data_type="string",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["etf"],
        ),
        "aum": schema_field(
            title="Assets Under Management",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["etf"],
        ),
        "holdings_count": schema_field(
            title="Holdings Count",
            data_type="integer",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["etf"],
        ),
        "tracking_error": schema_field(
            title="Tracking Error",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=["etf"],
        ),

        # --- Optional ESG ---
        "esg_score": schema_field(
            title="ESG Score",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
        "carbon_intensity": schema_field(
            title="Carbon Intensity",
            data_type="decimal",
            is_editable=False,
            is_system=True,
            is_default=False,
            subtype_labels=[],
        ),
    },

    "holding": {
        "quantity": schema_field(
            title="Quantity",
            data_type="decimal",
            is_editable=True,
            is_default=True,
            constraints={"decimal_places": 4},
            display_order=20,
            subtype_labels=[],
        ),
        "purchase_price": schema_field(
            title="Purchase Price",
            data_type="decimal",
            is_editable=True,
            is_default=True,
            constraints={"decimal_places": 2, "min": Decimal("0")},
            display_order=21,
            subtype_labels=[],
        ),
        "purchase_date": schema_field(
            title="Purchase Date",
            data_type="date",
            is_editable=True,
            is_default=True,
            display_order=22,
            subtype_labels=[],
        ),
    },

    "calculated": {
        "current_value_equity_fx": schema_field(
            title="Current Value - Equity FX",
            data_type="decimal",
            formula_key="current_value_equity_fx",
            is_editable=False,
            is_default=True,
            constraints={"decimal_places": 2, "min": Decimal("0")},
            display_order=30,
            subtype_labels=[],
        ),
        "unrealized_gain": schema_field(
            title="Unrealized Gain",
            data_type="decimal",
            formula_key="unrealized_gain",
            is_editable=False,
            is_default=False,
            constraints={"decimal_places": 2},
            subtype_labels=[],
        ),
    },
}
