from decimal import Decimal
from core.schema_config.utils import schema_field

REAL_ESTATE_SCHEMA_CONFIG = {
    "asset": {
        "symbol": schema_field(
            title="Symbol",
            data_type="string",
            is_editable=False,
            is_deletable=False,
            is_default=True,
            is_system=True,
            constraints={"character_limit": 20},
            display_order=1,
        ),
        "name": schema_field(
            title="Name",
            data_type="string",
            is_editable=True,
            is_deletable=False,
            is_default=True,
            is_system=True,
            constraints={"character_limit": 200},
            display_order=2,
        ),
        "location": schema_field(
            title="Location",
            data_type="string",
            is_editable=True,
            is_default=True,
            constraints={"character_limit": 255},
            display_order=3,
        ),
        "property_type": schema_field(
            title="Property Type",
            data_type="string",
            is_editable=True,
            is_default=True,
            display_order=4,
        ),
        "currency": schema_field(
            title="Currency",
            data_type="string",
            is_editable=False,
            is_default=True,
            is_system=True,
            constraints={"character_limit": 3, "all_caps": True},
            display_order=5,
        ),
    },
    "holding": {
        "purchase_price": schema_field(
            title="Purchase Price",
            data_type="decimal",
            is_editable=True,
            is_default=True,
            constraints={"decimal_places": 2, "min": Decimal("0")},
            display_order=6,
        ),
        "estimated_value": schema_field(
            title="Estimated Value",
            data_type="decimal",
            is_editable=True,
            is_default=True,
            constraints={"decimal_places": 2, "min": Decimal("0")},
            display_order=7,
        ),
        "rental_income": schema_field(
            title="Rental Income",
            data_type="decimal",
            is_editable=True,
            is_default=False,
            constraints={"decimal_places": 2, "min": Decimal("0")},
        ),
        "expenses": schema_field(
            title="Expenses",
            data_type="decimal",
            is_editable=True,
            is_default=False,
            constraints={"decimal_places": 2, "min": Decimal("0")},
        ),
        "mortgage_balance": schema_field(
            title="Mortgage Balance",
            data_type="decimal",
            is_editable=True,
            is_default=False,
            constraints={"decimal_places": 2, "min": Decimal("0")},
        ),
    },
    "calculated": {
        "owner_equity": schema_field(
            title="Equity",
            data_type="decimal",
            formula_key="owner_equity",
            is_editable=False,
            is_default=True,
            constraints={"decimal_places": 2},
            display_order=8,
        ),
        "net_rental_yield": schema_field(
            title="Net Rental Yield (%)",
            data_type="decimal",
            formula_key="net_rental_yield",
            is_editable=False,
            is_default=False,
            constraints={"decimal_places": 2},
        ),
        "loan_to_value": schema_field(
            title="Loan-to-Value Ratio",
            data_type="decimal",
            formula_key="loan_to_value",
            is_editable=False,
            is_default=False,
            constraints={"decimal_places": 2},
        ),
    },
}
