# Generated by Django 6.0.2 on 2026-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('broker', models.CharField(blank=True, help_text='Optional broker name.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('position_mode', models.CharField(choices=[('manual', 'Manual'), ('synced', 'Synced'), ('ledger', 'Ledger'), ('hybrid', 'Hybrid')], default='manual', help_text='How holdings are maintained for this account.', max_length=20)),
                ('allow_manual_overrides', models.BooleanField(default=True, help_text='Whether users can manually adjust holdings when account is synced.')),
            ],
            options={
                'ordering': ['portfolio', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Annual contribution limit for this user (if applicable).', max_digits=20, null=True)),
                ('carry_forward_room', models.DecimalField(blank=True, decimal_places=2, help_text='Unused contribution room carried forward.', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['definition__name'],
            },
        ),
        migrations.CreateModel(
            name='AccountJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('sync_positions', 'Sync Positions'), ('sync_transactions', 'Sync Transactions'), ('reconcile', 'Reconcile'), ('snapshot', 'Snapshot')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('run_after', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('interest', 'Interest'), ('fee', 'Fee'), ('tax', 'Tax'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('plaid', 'Plaid'), ('import', 'Import')], default='manual', max_length=20)),
                ('external_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('traded_at', models.DateTimeField()),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-traded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='System identifier (only for system-defined account types).', null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrokerageConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('brokerage', 'Brokerage'), ('crypto_exchange', 'Crypto Exchange'), ('wallet', 'Wallet')], default='brokerage', max_length=30)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('plaid', 'Plaid'), ('alpaca', 'Alpaca'), ('coinbase', 'Coinbase'), ('kraken', 'Kraken'), ('wallet_connect', 'Wallet Connect')], max_length=30)),
                ('external_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('connection_label', models.CharField(blank=True, max_length=255, null=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerageSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(max_length=30)),
                ('secret_ciphertext', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('tax_deferred', 'Tax-Deferred'), ('tax_exempt', 'Tax-Exempt')], default='taxable', max_length=50)),
                ('all_countries', models.BooleanField(default=False, help_text='If true, this classification applies globally (all countries).')),
                ('is_system', models.BooleanField(default=True, help_text='True if this is a built-in classification available globally.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_ticker', models.CharField(blank=True, db_index=True, help_text='Ticker used when this holding was market-backed.', max_length=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=30, default=0, help_text='Total quantity of this asset held in the account.', max_digits=50)),
                ('average_purchase_price', models.DecimalField(blank=True, decimal_places=30, help_text='Weighted average purchase price per unit.', max_digits=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account', 'asset'],
            },
        ),
        migrations.CreateModel(
            name='HoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=30, max_digits=50)),
                ('average_purchase_price', models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('value_profile_currency', models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True)),
                ('source', models.CharField(default='system', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-as_of', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(choices=[('missing_internal_holding', 'Missing Internal Holding'), ('missing_external_holding', 'Missing External Holding'), ('quantity_mismatch', 'Quantity Mismatch'), ('symbol_unmapped', 'Symbol Unmapped'), ('stale_sync', 'Stale Sync')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolution_action', models.CharField(blank=True, choices=[('keep_internal', 'Keep Internal'), ('align_to_external', 'Align To External'), ('adjust_internal_quantity', 'Adjust Internal Quantity'), ('ignore', 'Ignore')], max_length=40, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=500, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
