# Generated by Django 6.0.2 on 2026-03-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_allowed_asset_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='classificationdefinition',
            name='countries',
        ),
        migrations.DeleteModel(
            name='AccountClassification',
        ),
        migrations.DeleteModel(
            name='ClassificationDefinition',
        ),
    ]
