# Generated by Django 6.0.2 on 2026-03-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_account_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='price_source_mode',
            field=models.CharField(choices=[('account_default', 'Account Default'), ('market', 'Market'), ('manual', 'Manual'), ('unavailable', 'Unavailable')], default='account_default', help_text='How this holding should be valued when price data is resolved.', max_length=20),
        ),
        migrations.AddField(
            model_name='holding',
            name='tracking_mode',
            field=models.CharField(choices=[('account_default', 'Account Default'), ('tracked', 'Tracked'), ('manual', 'Manual')], default='account_default', help_text='Whether this holding follows the account default, is tracked automatically, or is managed manually.', max_length=20),
        ),
    ]
