def precious_metals_schema_template():
    return {
        "account_type_slug": "precious-metal",
        "name": "Precious Metals Schema Template",
        "description": "Default schema template for precious metal holdings.",
        "columns": [
            {
                "title": "Metal",
                "identifier": "metal",
                "data_type": "string",
                "source": "asset",
                "source_field": "precious_metal__metal",
                "is_system": True,
                "is_editable": False,
                "is_deletable": False,
                "is_default": True,
                "display_order": 1,
            },
            {
                "title": "Unit",
                "identifier": "unit",
                "data_type": "string",
                "source": "asset",
                "source_field": "precious_metal__unit",
                "is_system": True,
                "is_editable": False,
                "is_deletable": False,
                "is_default": True,
                "display_order": 2,
            },
            {
                "title": "Purchase Price",
                "identifier": "purchase_price",
                "data_type": "decimal",
                "source": "holding",
                "source_field": "average_purchase_price",
                "is_system": True,
                "is_editable": True,
                "is_deletable": False,
                "is_default": True,
                "display_order": 3,
                "constraints": {"decimal_places": 2},
            },
            {
                "title": "Quantity",
                "identifier": "quantity",
                "data_type": "decimal",
                "source": "holding",
                "source_field": "quantity",
                "is_system": True,
                "is_editable": True,
                "is_deletable": False,
                "is_default": True,
                "display_order": 4,
                "constraints": {"decimal_places": 6},
            },
            {
                "title": "Last Price",
                "identifier": "last_price",
                "data_type": "decimal",
                "source": "asset",
                "source_field": "price__price",
                "is_system": True,
                "is_editable": False,
                "is_deletable": False,
                "is_default": True,
                "display_order": 5,
                "constraints": {"decimal_places": 2},
            },
            {
                "title": "Current Value",
                "identifier": "current_value",
                "data_type": "decimal",
                "source": "formula",
                "source_field": "current_value_profile_fx",
                "is_system": True,
                "is_editable": False,
                "is_deletable": False,
                "is_default": True,
                "display_order": 6,
                "constraints": {"decimal_places": 2},
            },
        ],
    }
