# Generated by Django 6.0.2 on 2026-02-19 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_brokeragesecret'),
        ('assets', '0002_delete_realestatecashflow'),
        ('portfolios', '0004_remove_is_main'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('value_identifier', models.SlugField(default='current_value', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('dimension_type', models.CharField(choices=[('categorical', 'Categorical'), ('weighted', 'Weighted')], default='categorical', max_length=20)),
                ('source_type', models.CharField(choices=[('scv_identifier', 'SCV Identifier'), ('asset_exposure', 'Asset Exposure'), ('holding_exposure', 'Holding Exposure')], default='scv_identifier', max_length=30)),
                ('source_identifier', models.SlugField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='analytics.analytic')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analytics.analytic')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytic_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DimensionBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('is_unknown_bucket', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='analytics.analyticdimension')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='analytics.dimensionbucket')),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AssetDimensionExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source', models.CharField(choices=[('system', 'System'), ('user', 'User')], default='user', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytic_exposures', to='assets.asset')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_exposures', to='analytics.analyticdimension')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_exposures', to='analytics.dimensionbucket')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_label_snapshot', models.CharField(max_length=150)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=6, max_digits=9)),
                ('holding_count', models.PositiveIntegerField(default=0)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='analytics.analyticdimension')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.analyticrun')),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='analytics.dimensionbucket')),
            ],
            options={
                'ordering': ['-total_value'],
            },
        ),
        migrations.CreateModel(
            name='HoldingDimensionExposureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_exposure_overrides', to='analytics.dimensionbucket')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_exposure_overrides', to='analytics.analyticdimension')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytic_exposure_overrides', to='accounts.holding')),
            ],
        ),
        migrations.AddIndex(
            model_name='analytic',
            index=models.Index(fields=['portfolio', 'is_active'], name='analytics_a_portfol_d20438_idx'),
        ),
        migrations.AddConstraint(
            model_name='analytic',
            constraint=models.UniqueConstraint(fields=('portfolio', 'name'), name='uniq_analytic_name_per_portfolio'),
        ),
        migrations.AddIndex(
            model_name='analyticdimension',
            index=models.Index(fields=['analytic', 'is_active', 'display_order'], name='analytics_a_analyti_d691a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticdimension',
            constraint=models.UniqueConstraint(fields=('analytic', 'name'), name='uniq_dimension_name_per_analytic'),
        ),
        migrations.AddIndex(
            model_name='analyticrun',
            index=models.Index(fields=['analytic', '-created_at'], name='analytics_a_analyti_b8a078_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticrun',
            index=models.Index(fields=['status'], name='analytics_a_status_bc5e79_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionbucket',
            index=models.Index(fields=['dimension', 'is_active', 'display_order'], name='analytics_d_dimensi_b105e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='dimensionbucket',
            constraint=models.UniqueConstraint(fields=('dimension', 'key'), name='uniq_bucket_key_per_dimension'),
        ),
        migrations.AddIndex(
            model_name='assetdimensionexposure',
            index=models.Index(fields=['dimension', 'asset'], name='analytics_a_dimensi_3562f0_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdimensionexposure',
            index=models.Index(fields=['dimension', 'bucket'], name='analytics_a_dimensi_8d43f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetdimensionexposure',
            constraint=models.UniqueConstraint(fields=('dimension', 'asset', 'bucket'), name='uniq_asset_bucket_exposure'),
        ),
        migrations.AddConstraint(
            model_name='assetdimensionexposure',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 1)), name='asset_exposure_weight_between_0_and_1'),
        ),
        migrations.AddIndex(
            model_name='analyticresult',
            index=models.Index(fields=['run', 'dimension'], name='analytics_a_run_id_f78225_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticresult',
            constraint=models.UniqueConstraint(fields=('run', 'dimension', 'bucket_label_snapshot'), name='uniq_result_bucket_per_run_dimension'),
        ),
        migrations.AddIndex(
            model_name='holdingdimensionexposureoverride',
            index=models.Index(fields=['dimension', 'holding'], name='analytics_h_dimensi_432a64_idx'),
        ),
        migrations.AddIndex(
            model_name='holdingdimensionexposureoverride',
            index=models.Index(fields=['dimension', 'bucket'], name='analytics_h_dimensi_2fab17_idx'),
        ),
        migrations.AddConstraint(
            model_name='holdingdimensionexposureoverride',
            constraint=models.UniqueConstraint(fields=('dimension', 'holding', 'bucket'), name='uniq_holding_bucket_exposure_override'),
        ),
        migrations.AddConstraint(
            model_name='holdingdimensionexposureoverride',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 1)), name='holding_exposure_weight_between_0_and_1'),
        ),
    ]
