# Generated by Django 5.2.8 on 2025-11-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal identifier for this analytic (unique per portfolio).', max_length=100)),
                ('label', models.CharField(help_text="User-visible label, e.g. 'Country Exposure'.", max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this analytic measures.', null=True)),
                ('value_identifier', models.CharField(help_text="SchemaColumn identifier used for aggregation (e.g., 'current_value_profile_fx').", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(help_text='The portfolio this analytic belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('portfolio', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal identifier for this dimension (unique per analytic).', max_length=100)),
                ('label', models.CharField(help_text="User-facing label (e.g. 'Country', 'Sector').", max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_identifier', models.CharField(help_text="SchemaColumn identifier used to group holdings (e.g. 'country', 'sector').", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='analytics.analytic')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('analytic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticDimensionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_value', models.CharField(help_text='Total aggregated numeric value for this bucket.', max_length=255)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total aggregated numeric value for this bucket.', max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=4, help_text='Percentage of the analytic total that this bucket represents.', max_digits=10)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='analytics.analyticdimension')),
            ],
            options={
                'ordering': ['dimension_value'],
                'unique_together': {('dimension', 'dimension_value')},
            },
        ),
    ]
