# Generated by Django 6.0.1 on 2026-01-16 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='portfolio',
            field=models.ForeignKey(help_text='The portfolio this analytic belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='analyticdimension',
            name='analytic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='analytics.analytic'),
        ),
        migrations.AddField(
            model_name='analyticdimensionvalue',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='analytics.analyticdimension'),
        ),
        migrations.AlterUniqueTogether(
            name='analytic',
            unique_together={('portfolio', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='analyticdimension',
            unique_together={('analytic', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='analyticdimensionvalue',
            unique_together={('dimension', 'dimension_value')},
        ),
    ]
