# apps/schemas/config/schema_template_config.py

SCHEMA_TEMPLATE_CONFIG = {
    "equity_self": {
        "name": "Equity – Self-Managed Account",
        "description": "Standard schema for user-managed stock brokerage accounts.",
        "columns": [
            {
                "title": "Ticker",
                "identifier": "ticker",
                "data_type": "string",
                "source": "asset",
                "source_field": "symbol",
                "is_system": True,
                "is_editable": False,
                "display_order": 1,
                "default_constraints": {"max_length": 10},
            },
            {
                "title": "Quantity",
                "identifier": "quantity",
                "data_type": "decimal",
                "source": "holding",
                "source_field": "quantity",
                "is_system": True,
                "is_editable": True,
                "display_order": 2,
                "default_constraints": {"decimal_places": 4, "min_value": 0},
            },
            {
                "title": "Market Price",
                "identifier": "market_price",
                "data_type": "decimal",
                "source": "asset",
                "source_field": "price",
                "is_system": True,
                "is_editable": False,
                "display_order": 3,
                "default_constraints": {"decimal_places": 2, "min_value": 0},
            },
            {
                "title": "Total Value",
                "identifier": "total_value",
                "data_type": "decimal",
                "source": "formula",
                "source_field": None,
                "is_system": True,
                "is_editable": False,
                "display_order": 4,
                "default_constraints": {"decimal_places": 2, "min_value": 0},
            },
        ],
    },

    "crypto_wallet": {
        "name": "Crypto Wallet",
        "description": "Schema for cryptocurrency wallets.",
        "columns": [
            {
                "title": "Token",
                "identifier": "token_name",
                "data_type": "string",
                "source": "asset",
                "source_field": "name",
                "is_system": True,
                "is_editable": False,
                "display_order": 1,
                "default_constraints": {"max_length": 50},
            },
            {
                "title": "Balance",
                "identifier": "balance",
                "data_type": "decimal",
                "source": "holding",
                "source_field": "quantity",
                "is_system": True,
                "is_editable": True,
                "display_order": 2,
                "default_constraints": {"decimal_places": 8, "min_value": 0},
            },
            {
                "title": "Market Value",
                "identifier": "market_value",
                "data_type": "decimal",
                "source": "formula",
                "source_field": None,
                "is_system": True,
                "is_editable": False,
                "display_order": 3,
                "default_constraints": {"decimal_places": 2, "min_value": 0},
            },
        ],
    },
}
