# Generated by Django 6.0.1 on 2026-01-19 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_holding'),
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('identifier', models.SlugField(help_text='Stable formula identifier (snake_case).', max_length=100, unique=True)),
                ('expression', models.TextField(help_text='Formula expression using column identifiers.')),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('applies_to', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], db_index=True, max_length=20)),
                ('default_string', models.CharField(blank=True, max_length=255, null=True)),
                ('default_decimal', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('default_integer', models.IntegerField(blank=True, null=True)),
                ('min_decimal', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('max_decimal', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
            ],
            options={
                'ordering': ['applies_to', 'label'],
                'unique_together': {('applies_to', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(help_text='AccountType this schema applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='accounts.accounttype')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['account_type__slug'],
                'unique_together': {('portfolio', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], max_length=20)),
                ('source', models.CharField(choices=[('holding', 'Holding'), ('asset', 'Asset'), ('formula', 'Formula'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, help_text='Required for asset/holding sources.', max_length=100, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='columns', to='schemas.formula')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.schema')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('schema', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='SchemaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.OneToOneField(help_text='AccountType this template applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='schema_template', to='accounts.accounttype')),
            ],
            options={
                'ordering': ['account_type__slug'],
            },
        ),
        migrations.CreateModel(
            name='SchemaColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('system', 'System'), ('formula', 'Formula'), ('user', 'User Override')], db_index=True, default='system', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='schemas.schemacolumn')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_values', to='accounts.holding')),
            ],
            options={
                'unique_together': {('column', 'holding')},
            },
        ),
        migrations.CreateModel(
            name='SchemaConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('applies_to', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], max_length=20)),
                ('value_string', models.CharField(blank=True, max_length=255, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('min_decimal', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('max_decimal', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('min_integer', models.IntegerField(blank=True, null=True)),
                ('max_integer', models.IntegerField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints_set', to='schemas.schemacolumn')),
            ],
            options={
                'unique_together': {('column', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchemaTemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.SlugField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('decimal', 'Decimal'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('url', 'URL')], max_length=20)),
                ('source', models.CharField(choices=[('holding', 'Holding'), ('asset', 'Asset'), ('formula', 'Formula'), ('custom', 'Custom')], max_length=20)),
                ('source_field', models.CharField(blank=True, help_text='Holding/Asset field name OR unused when formula is provided.', max_length=100, null=True)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_deletable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(blank=True, null=True)),
                ('formula', models.ForeignKey(blank=True, help_text="Formula to use when source='formula'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_columns', to='schemas.formula')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='schemas.schematemplate')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('template', 'identifier')},
            },
        ),
    ]
