# Generated by Django 5.2.1 on 2025-05-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('exchange', models.CharField(blank=True, help_text='Stock exchange (e.g., NYSE, NASDAQ)', max_length=50, null=True)),
                ('is_adr', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('average_volume', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quote_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker'], name='stocks_stoc_ticker_5df4c9_idx'), models.Index(fields=['is_custom'], name='stocks_stoc_is_cust_ed0f0f_idx'), models.Index(fields=['exchange'], name='stocks_stoc_exchang_2c4de0_idx')],
            },
        ),
    ]
