# Generated by Django 5.2.1 on 2025-05-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='last_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='investment_theme',
        ),
    ]
