# Generated by Django 5.2.1 on 2025-05-20 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomStock',
        ),
        migrations.DeleteModel(
            name='InvalidTicker',
        ),
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['ticker'], name='stocks_stoc_ticker_5df4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['is_custom'], name='stocks_stoc_is_cust_ed0f0f_idx'),
        ),
    ]
