# Generated by Django 5.2.1 on 2025-05-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_last_price_stock_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='average_volume_10d',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='day_high',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='day_low',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dividend_rate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dividend_yield',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ex_dividend_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fifty_two_week_high',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fifty_two_week_low',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='forward_pe',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='full_time_employees',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='long_business_summary',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='payout_ratio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='previous_close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price_to_book',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='website',
        ),
    ]
