# Generated by Django 5.2.1 on 2025-05-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_delete_customstock_delete_invalidticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, help_text='Stock exchange (e.g., NYSE, NASDAQ)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['exchange'], name='stocks_stoc_exchang_2c4de0_idx'),
        ),
    ]
