# Generated by Django 5.2.1 on 2025-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_exchange_stock_stocks_stoc_exchang_2c4de0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_adr',
            field=models.BooleanField(default=False),
        ),
    ]
