# Generated by Django 5.2.1 on 2025-05-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_customstock_rename_long_name_stock_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customstock',
            name='average_volume',
        ),
        migrations.RemoveField(
            model_name='customstock',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='customstock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='customstock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customstock',
            name='pe_ratio',
        ),
        migrations.RemoveField(
            model_name='customstock',
            name='price',
        ),
        migrations.RemoveField(
            model_name='customstock',
            name='quote_type',
        ),
        migrations.RemoveField(
            model_name='customstock',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='customstock',
            name='volume',
        ),
    ]
