# Generated by Django 5.2.1 on 2025-05-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_customstock_average_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
