# Generated by Django 5.2.1 on 2025-05-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
